# Project: Data Cleaning and Manipulation with Pandas

Task description:

## Technical Requirements

* Import the data using Pandas.
* Examine the data for potential issues.
* Use at least 8 of the cleaning and manipulation methods you have learned on the data.
* Produce a Jupyter Notebook that shows the steps you took and the code you used to clean and transform your data set.
* Export a clean CSV version of your data using Pandas.

## Necessary Deliverables

The following deliverables should be pushed to your Github repo for this chapter.

* **A cleaned CSV data file** containing the results of your data wrangling work.
* **A Jupyter Notebook (data-wrangling.ipynb)** containing all Python code and commands used in the importing, cleaning, manipulation, and exporting of your data set.
* **A ``README.md`` file** containing a detailed explanation of the process followed in the importing, cleaning, manipulation, and exporting of your data as well as your results, obstacles encountered, and lessons learned.

In [1]:
# Import required
import pandas as pd
import numpy as np
import re

In [2]:
# Import the data using pandas
df = pd.read_csv("sharkattack.csv", sep=",", engine="python")

In [3]:
## Examine the dataset for potential issues

# display df

df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [4]:
# display column names

df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [5]:
# display column types

df.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [6]:
# display missing cell count per column

df.isna().sum()

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [7]:
# Unnamed 22 and 23 can be dropped for sure

df = df.drop(['Unnamed: 22', 'Unnamed: 23'],axis=1)

In [8]:
# Case numbers seem to be duplicates

df = df.drop(['Case Number.1', 'Case Number.2'],axis=1)

In [9]:
# Check if href formula and href are duplicates

print(df.loc[0,"href formula"])
print(df.loc[0,"href"])

# Create column showing whether they are duplicate

df["href_equal"] = df["href formula"] == df["href"]

http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf

In [10]:
# Check number of href duplicate

df["href_equal"].value_counts()

True     5938
False      54
Name: href_equal, dtype: int64

In [11]:
# Compare all unequal rows

href_unequal_df = df.loc[df["href_equal"]==False, ["href formula","href"]]

In [12]:
href_unequal_df

,href formula,href
20,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
27,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
61,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
107,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
114,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
134,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
180,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
193,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN
232,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
262,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
263,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
264,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
271,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
272,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
293,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
305,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
323,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
347,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
361,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
362,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
363,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
364,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
365,http://sharkattackfile.net/spreadsheets/pdf_di...,pdf_directory2014.01.04-Riano.pdf
367,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
377,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
378,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
379,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
380,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
381,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
382,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
383,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
384,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
448,pdf-directory/2013.05.27.b-Ena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
449,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
823,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1217,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1218,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2274,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN
2477,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3019,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3549,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3603,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3917,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3928,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4394,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4642,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4668,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4719,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5317,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5458,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5686,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN
5694,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5819,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5857,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [13]:
# Look at the columns values, do they link to the same object?

print(href_unequal_df.loc[27,"href formula"])
print(href_unequal_df.loc[27,"href"])

http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.23.a-Cutbirth.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.23-Cutbirth.pdf

In [14]:
# Saw a NaN in the second column. Count for NaNs

href_unequal_df.isna().sum()

href formula    1
href            3
dtype: int64

In [15]:
# Copy href to href formula where href formula is NaN. Drop href column.

df.loc[pd.isna(df["href formula"]), ["href formula"]] = df["href"]

In [16]:
# Check if it worked

df["href formula"].isna().sum()

0

In [17]:
# Drop href column and href_equal helper column, rename href formula column

df = df.drop(["href","href_equal"],axis=1)

df = df.rename(columns={"href formula":"href"})

In [18]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,4
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,3
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2

In [19]:
# Check what pdf column is

print(df.loc[0,"pdf"])
print(df.loc[0,"href"])

2016.09.18.c-NSB.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf

In [20]:
# It's just another variation of href. drop pdf.

df = df.drop(columns="pdf",index=1)

In [21]:
# Check if some case numbers are duplicated

df["Case Number"].value_counts().gt(1)

1980.07.00       True
1962.06.11.b     True
1966.12.26       True
1923.00.00.a     True
2014.08.02       True
                ...
1878.11.17      False
1992.11.12.R    False
1903.00.00.b    False
1983.08.06      False
1908.06.02.R    False
Name: Case Number, Length: 5975, dtype: bool

In [22]:
# Look into duplicated case number rows

dupdf = df[df.duplicated(['Case Number'])]
dupdf

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,href,original order
301,2014.08.02,02-Aug-14,2014,Unprovoked,USA,Florida,"Table Beach, Brevard County",Boogie boarding,Christian Sanhueza,M,8,Laceration to ankle,N,13h00,NaN,"Florida Today, 8/2/2014",http://sharkattackfile.net/spreadsheets/pdf_di...,5691
393,2013.10.05,10-Oct-13,2013,Unprovoked,USA,Florida,"Destin, Okaloosa County",Wading,Zachary Tyke Standridge,M,12,Lacerations to right forearm,N,15h30,Small bull shark,"Monroe County Advocate, 10/9/2013",http://sharkattackfile.net/spreadsheets/pdf_di...,5600
524,2012.09.02.b,02-Sep-12,2012,Provoked,USA,Hawaii,"Spreckelsville, Maui",Spearfishing,M. Malabon,NaN,NaN,Minor laceration to hand PROVOKED INCIDENT,N,12h00,"Tiger shark, 10' to 12'",HawaiiNow.com,http://sharkattackfile.net/spreadsheets/pdf_di...,5469
841,2009.12.18,18-Dec-09,2009,Invalid,SOUTH AFRICA,KwaZulu-Natal,"North Beach, Durban",Surfing,Lance Morris,M,NaN,Minor lacerations to left leg. nitially report...,N,NaN,No shark involvement,"M. Addison, C. Eckstander, GSAF",http://sharkattackfile.net/spreadsheets/pdf_di...,5152
1213,2006.09.02,02-Sep-06,2006,Unprovoked,SOUTH AFRICA,Western Cape Province,Noordhoek,Surfing,Steven Harcourt-Wood,M,37,"No injury, shark rammed surfboard",N,NaN,"White shark, 3.5m","Cape Times, 9/3/2006",http://sharkattackfile.net/spreadsheets/pdf_di...,4780
1376,2005.04.06,06-Apr-05,2005,Invalid,HONDURAS,Bay Islands,Utila,SCUBA Diving,female,F,NaN,"Laceration on siide of calf, small laceration ...",N,NaN,Shark involvement not confirmed,"J. Engel, SRI & S. Fox, Deep Blue",http://sharkattackfile.net/spreadsheets/pdf_di...,4617
2410,1990.05.10,10-May-90,1990,Unprovoked,AUSTRALIA,Queensland,Outer Barrier Reef near Port Douglas,"Snorkeling, possibly holding a fish",German male,M,30s,Lacerations,N,NaN,2 m hammerhead,"Courier-Mail, 5/11/1990, p.1",http://sharkattackfile.net/spreadsheets/pdf_di...,3584
2713,1983.06.15,15-Jun-83,1983,Invalid,ITALY,Northwest Italy,Riomaggiore (Ligura),Scuba diving,Roberto Piaviali,M,NaN,"No injury, shark ""harassed"" him at depth of 5 m",N,NaN,3 m [10'] white shark,MEDSAF,http://sharkattackfile.net/spreadsheets/pdf_di...,3280
2838,1980.07.00,Early Jul-1980,1980,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Tom Durrance,M,NaN,Lower leg bitten,N,NaN,NaN,"Daytona Beach Morning Journal, 7/9/1980",http://sharkattackfile.net/spreadsheets/pdf_di...,3155
3318,1966.12.26,26-Dec-66,1966,Unprovoked,AUSTRALIA,New South Wales,Coogee,Spearfishing,David Jensen,M,29,Right leg bitten,N,NaN,1.8 m [6'] shark,"Sun (Sydney), 12/29/1966; H.D. Baldridge, p.137",http://sharkattackfile.net/spreadsheets/pdf_di...,2675
3589,1962.06.11.b,11-Jun-62,1962,Unprovoked,USA,California,San Francisco Bay,Escaping from Alacatraz,John William Anglin,M,32,"FATAL, but shark involvement uncomfirmed. Deat...",Y,Night,NaN,"San Francisco Chronicle, 5/3/1986",http://sharkattackfile.net/spreadsheets/pdf_di...,2404
4983,1923.00.00.a,1923,1922,Provoked,USA,New Jersey,Ocean City (offshore),Hoisting shark aboard fishing boat,male,M,NaN,Shark's tail broke his leg. PROVOKED INCIDENT,N,NaN,NaN,"Ref in New York Herald Tribune, 8/23/1960; V.M...",http://sharkattackfile.net/spreadsheets/pdf_di...,1010
5029,1920.00.00.b,1920,1920,Unprovoked,NEW ZEALAND,North Island,"Stanley Bay, Auckland Harbor",NaN,female,F,NaN,"""Recovered""",N,NaN,NaN,"V.M. Coppleson (1958), p.262",http://sharkattackfile.net/spreadsheets/pdf_di...,964
5091,1915.07.06.a.R,Reported 06-Jul-1915,1915,Unprovoked,MEXICO,NaN,Santa Maria Bar,Wading,J.W. McDonald,M,NaN,FATAL,Y,NaN,NaN,"Oakland Tribune, 7/6/1915",http://sharkattackfile.net/spreadsheets/pdf_di...,902
5121,1913.08.27.R,Reported 27-Aug-1913,1913,Invalid,USA,New Jersey,"Spring Lake, Monmouth County",NaN,NaN,F,NaN,Female foot recovered from shark,UNKNOWN,NaN,NaN,"Washington Post, 8/27/1913",http://sharkattackfile.net/spreadsheets/pdf_di...,872
5208,1907.10.16.R,Reported 16-Oct-1907,1907,Unprovoked,CHINA,Hong Kong,"Sharp Peak, Sai Kung Peninsula, New Territories",Fishing,fishermen,M,NaN,2 of the 5 fishermen were so seriously injure...,Y,NaN,Shark involvement probable,"Dawson Daily News, 11/20/1907",http://sharkattackfile.net/spreadsheets/pdf_di...,785

In [23]:
# Check if any rows in the whole df are duplicates

df.duplicated().value_counts()

False    5991
dtype: int64

In [24]:
# Compare with number of duplicate case number rows

df.duplicated(['Case Number']).value_counts()

False    5975
True       16
dtype: int64

In [25]:
# Create list of duplicate case number columns

dup_case_no_list = list(df["Case Number"].value_counts().gt(1).index)
lis = dup_case_no_list

In [26]:
# Check if they are very similar, check one random item 6

df.loc[df['Case Number'] == lis[6]]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,href,original order
5207,1907.10.16.R,Reported 16-Oct-1907,1907,Unprovoked,CHINA,Hong Kong,"Sharp Peak, Sai Kung Peninsula, New Territories",Fishing,fishermen,M,NaN,"3 of thel 5 were injured, one of whom lost bot...",N,NaN,Shark involvement probable,"Dawson Daily News, 11/20/1907",http://sharkattackfile.net/spreadsheets/pdf_di...,786
5208,1907.10.16.R,Reported 16-Oct-1907,1907,Unprovoked,CHINA,Hong Kong,"Sharp Peak, Sai Kung Peninsula, New Territories",Fishing,fishermen,M,NaN,2 of the 5 fishermen were so seriously injure...,Y,NaN,Shark involvement probable,"Dawson Daily News, 11/20/1907",http://sharkattackfile.net/spreadsheets/pdf_di...,785

In [27]:
# Duplicate case numbers are not duplicate caes. Since case numbers just seem to be a variation of date, they can be dropped. 

df = df.drop(columns="Case Number")

In [28]:
# Check out date column values

lis = list(df["Date"].value_counts().index)

In [29]:
# Replace words such as reported, early and summer, mid, before

removelist = ["Reported", "reported", "Early", "early", "Summer", "summer", "mid", "Mid", "before", "Before"]

for i in removelist:
    df["Date"] = df["Date"].str.replace(i,"")

In [30]:
df["Date"].value_counts()

1957              11
1942               9
1956               8
1958               7
1941               7
                  ..
29-Dec-63          1
 30-March-1878     1
12-30-1980         1
12-Feb-88          1
 28-Mar-1928       1
Name: Date, Length: 5124, dtype: int64

In [31]:
# Furthermore, merge date and year columns into one uniform date format columns.

df['Date'] = pd.to_datetime(df['Date'], errors = "coerce")

In [32]:
# Check datetime

list(df["Date"].value_counts().index)

[Timestamp('1958-01-01 00:00:00'),
 Timestamp('1957-01-01 00:00:00'),
 Timestamp('1942-01-01 00:00:00'),
 Timestamp('1956-01-01 00:00:00'),
 Timestamp('1950-01-01 00:00:00'),
 Timestamp('1941-01-01 00:00:00'),
 Timestamp('1960-01-01 00:00:00'),
 Timestamp('1898-01-01 00:00:00'),
 Timestamp('1959-01-01 00:00:00'),
 Timestamp('2060-10-01 00:00:00'),
 Timestamp('2056-08-01 00:00:00'),
 Timestamp('1949-01-01 00:00:00'),
 Timestamp('1876-01-01 00:00:00'),
 Timestamp('1952-01-01 00:00:00'),
 Timestamp('1954-01-01 00:00:00'),
 Timestamp('1971-01-01 00:00:00'),
 Timestamp('1955-01-01 00:00:00'),
 Timestamp('2001-04-12 00:00:00'),
 Timestamp('1940-01-01 00:00:00'),
 Timestamp('1961-01-01 00:00:00'),
 Timestamp('2003-10-05 00:00:00'),
 Timestamp('1938-01-01 00:00:00'),
 Timestamp('1995-07-28 00:00:00'),
 Timestamp('1911-01-01 00:00:00'),
 Timestamp('1948-01-01 00:00:00'),
 Timestamp('2060-04-01 00:00:00'),
 Timestamp('1890-01-01 00:00:00'),
 Timestamp('1998-01-01 00:00:00'),
 Timestamp('1970-01-23 00:00:00'),
 Timestamp('1906-01-01 00:00:00'),
 Timestamp('2012-01-01 00:00:00'),
 Timestamp('1883-01-01 00:00:00'),
 Timestamp('1945-01-01 00:00:00'),
 Timestamp('1929-01-01 00:00:00'),
 Timestamp('2010-01-09 00:00:00'),
 Timestamp('2009-07-24 00:00:00'),
 Timestamp('1926-01-01 00:00:00'),
 Timestamp('2015-09-20 00:00:00'),
 Timestamp('1930-01-01 00:00:00'),
 Timestamp('1996-01-01 00:00:00'),
 Timestamp('2008-12-27 00:00:00'),
 Timestamp('2052-07-27 00:00:00'),
 Timestamp('2008-06-26 00:00:00'),
 Timestamp('1994-07-09 00:00:00'),
 Timestamp('1985-01-01 00:00:00'),
 Timestamp('2012-06-14 00:00:00'),
 Timestamp('2014-12-28 00:00:00'),
 Timestamp('1995-01-01 00:00:00'),
 Timestamp('1943-01-01 00:00:00'),
 Timestamp('1906-10-10 00:00:00'),
 Timestamp('1965-01-01 00:00:00'),
 Timestamp('1962-01-01 00:00:00'),
 Timestamp('2011-06-06 00:00:00'),
 Timestamp('1905-01-01 00:00:00'),
 Timestamp('2011-08-17 00:00:00'),
 Timestamp('1981-01-01 00:00:00'),
 Timestamp('2004-05-22 00:00:00'),
 Timestamp('2001-08-19 00:00:00'),
 Timestamp('2003-06-24 00:00:00'),
 Timestamp('2002-09-27 00:00:00'),
 Timestamp('2003-10-31 00:00:00'),
 Timestamp('2008-06-28 00:00:00'),
 Timestamp('1913-01-01 00:00:00'),
 Timestamp('2064-02-01 00:00:00'),
 Timestamp('2014-06-01 00:00:00'),
 Timestamp('2014-08-27 00:00:00'),
 Timestamp('2010-05-18 00:00:00'),
 Timestamp('2004-07-27 00:00:00'),
 Timestamp('2012-09-02 00:00:00'),
 Timestamp('2013-06-25 00:00:00'),
 Timestamp('1982-08-29 00:00:00'),
 Timestamp('2013-07-28 00:00:00'),
 Timestamp('1968-01-01 00:00:00'),
 Timestamp('2062-01-11 00:00:00'),
 Timestamp('2006-08-20 00:00:00'),
 Timestamp('2009-03-06 00:00:00'),
 Timestamp('2060-11-01 00:00:00'),
 Timestamp('1903-01-01 00:00:00'),
 Timestamp('1886-08-01 00:00:00'),
 Timestamp('1974-01-07 00:00:00'),
 Timestamp('1998-05-16 00:00:00'),
 Timestamp('2058-07-01 00:00:00'),
 Timestamp('2001-04-11 00:00:00'),
 Timestamp('2003-09-14 00:00:00'),
 Timestamp('1997-08-11 00:00:00'),
 Timestamp('2007-08-19 00:00:00'),
 Timestamp('1953-01-01 00:00:00'),
 Timestamp('2005-04-06 00:00:00'),
 Timestamp('2053-03-01 00:00:00'),
 Timestamp('2061-12-28 00:00:00'),
 Timestamp('2001-08-18 00:00:00'),
 Timestamp('2042-11-01 00:00:00'),
 Timestamp('1974-08-16 00:00:00'),
 Timestamp('2013-09-21 00:00:00'),
 Timestamp('2064-01-01 00:00:00'),
 Timestamp('1992-03-08 00:00:00'),
 Timestamp('1991-07-01 00:00:00'),
 Timestamp('1982-01-01 00:00:00'),
 Timestamp('1999-03-18 00:00:00'),
 Timestamp('2016-07-08 00:00:00'),
 Timestamp('1972-01-01 00:00:00'),
 Timestamp('2012-07-07 00:00:00'),
 Timestamp('2014-03-18 00:00:00'),
 Timestamp('1904-01-01 00:00:00'),
 Timestamp('2012-06-26 00:00:00'),
 Timestamp('2014-06-09 00:00:00'),
 Timestamp('1871-01-01 00:00:00'),
 Timestamp('2003-04-20 00:00:00'),
 Timestamp('2009-01-24 00:00:00'),
 Timestamp('2013-09-01 00:00:00'),
 Timestamp('1999-01-01 00:00:00'),
 Timestamp('2016-07-12 00:00:00'),
 Timestamp('1996-02-09 00:00:00'),
 Timestamp('2015-10-17 00:00:00'),
 Timestamp('2015-06-24 00:00:00'),
 Timestamp('1973-01-01 00:00:00'),
 Timestamp('1899-08-08 00:00:00'),
 Timestamp('2034-04-01 00:00:00'),
 Timestamp('1963-01-01 00:00:00'),
 Timestamp('1927-01-01 00:00:00'),
 Timestamp('1977-03-13 00:00:00'),
 Timestamp('2062-06-11 00:00:00'),
 Timestamp('2008-03-28 00:00:00'),
 Timestamp('2010-02-06 00:00:00'),
 Timestamp('2061-02-01 00:00:00'),
 Timestamp('2016-07-07 00:00:00'),
 Timestamp('1939-01-01 00:00:00'),
 Timestamp('2061-01-06 00:00:00'),
 Timestamp('1923-01-01 00:00:00'),
 Timestamp('2062-01-14 00:00:00'),
 Timestamp('2005-11-25 00:00:00'),
 Timestamp('1997-05-31 00:00:00'),
 Timestamp('1999-12-31 00:00:00'),
 Timestamp('2014-05-14 00:00:00'),
 Timestamp('2066-05-20 00:00:00'),
 Timestamp('2008-08-30 00:00:00'),
 Timestamp('1946-01-01 00:00:00'),
 Timestamp('2015-06-26 00:00:00'),
 Timestamp('2007-09-30 00:00:00'),
 Timestamp('2000-09-08 00:00:00'),
 Timestamp('1921-01-01 00:00:00'),
 Timestamp('1885-07-26 00:00:00'),
 Timestamp('2005-04-16 00:00:00'),
 Timestamp('2066-08-27 00:00:00'),
 Timestamp('1989-08-22 00:00:00'),
 Timestamp('2008-05-07 00:00:00'),
 Timestamp('1990-08-19 00:00:00'),
 Timestamp('2040-07-13 00:00:00'),
 Timestamp('1995-04-09 00:00:00'),
 Timestamp('1849-06-08 00:00:00'),
 Timestamp('1984-10-21 00:00:00'),
 Timestamp('1882-11-12 00:00:00'),
 Timestamp('2065-11-03 00:00:00'),
 Timestamp('2063-12-26 00:00:00'),
 Timestamp('2002-01-30 00:00:00'),
 Timestamp('2060-02-27 00:00:00'),
 Timestamp('1970-09-01 00:00:00'),
 Timestamp('2002-10-05 00:00:00'),
 Timestamp('2015-08-18 00:00:00'),
 Timestamp('1974-01-01 00:00:00'),
 Timestamp('1776-01-01 00:00:00'),
 Timestamp('1975-07-30 00:00:00'),
 Timestamp('2058-07-04 00:00:00'),
 Timestamp('2001-01-24 00:00:00'),
 Timestamp('1986-12-06 00:00:00'),
 Timestamp('2067-08-01 00:00:00'),
 Timestamp('2004-01-21 00:00:00'),
 Timestamp('2047-11-14 00:00:00'),
 Timestamp('2013-03-10 00:00:00'),
 Timestamp('2029-03-04 00:00:00'),
 Timestamp('2000-11-06 00:00:00'),
 Timestamp('2011-10-29 00:00:00'),
 Timestamp('2044-10-25 00:00:00'),
 Timestamp('2006-02-12 00:00:00'),
 Timestamp('2067-11-30 00:00:00'),
 Timestamp('2012-01-18 00:00:00'),
 Timestamp('1975-11-19 00:00:00'),
 Timestamp('1988-07-04 00:00:00'),
 Timestamp('2008-07-24 00:00:00'),
 Timestamp('2002-11-28 00:00:00'),
 Timestamp('2000-07-04 00:00:00'),
 Timestamp('1984-01-01 00:00:00'),
 Timestamp('2037-10-24 00:00:00'),
 Timestamp('1996-07-23 00:00:00'),
 Timestamp('2006-07-29 00:00:00'),
 Timestamp('1997-02-28 00:00:00'),
 Timestamp('1894-06-15 00:00:00'),
 Timestamp('2001-04-13 00:00:00'),
 Timestamp('2012-03-14 00:00:00'),
 Timestamp('2013-04-13 00:00:00'),
 Timestamp('2012-06-22 00:00:00'),
 Timestamp('2000-09-10 00:00:00'),
 Timestamp('1990-05-10 00:00:00'),
 Timestamp('2016-07-13 00:00:00'),
 Timestamp('1970-06-13 00:00:00'),
 Timestamp('1993-08-15 00:00:00'),
 Timestamp('2014-02-07 00:00:00'),
 Timestamp('2041-11-27 00:00:00'),
 Timestamp('1894-04-28 00:00:00'),
 Timestamp('2016-03-28 00:00:00'),
 Timestamp('1994-01-31 00:00:00'),
 Timestamp('1997-08-14 00:00:00'),
 Timestamp('2013-08-26 00:00:00'),
 Timestamp('2007-04-20 00:00:00'),
 Timestamp('2016-06-15 00:00:00'),
 Timestamp('1994-07-08 00:00:00'),
 Timestamp('1989-01-20 00:00:00'),
 Timestamp('2012-06-02 00:00:00'),
 Timestamp('1996-04-25 00:00:00'),
 Timestamp('2012-04-19 00:00:00'),
 Timestamp('2013-03-21 00:00:00'),
 Timestamp('1983-07-25 00:00:00'),
 Timestamp('2059-01-17 00:00:00'),
 Timestamp('2014-08-09 00:00:00'),
 Timestamp('2016-06-05 00:00:00'),
 Timestamp('2007-09-22 00:00:00'),
 Timestamp('1986-10-01 00:00:00'),
 Timestamp('2046-02-10 00:00:00'),
 Timestamp('1995-08-10 00:00:00'),
 Timestamp('2065-05-01 00:00:00'),
 Timestamp('1897-03-15 00:00:00'),
 Timestamp('2000-07-02 00:00:00'),
 Timestamp('1998-04-01 00:00:00'),
 Timestamp('1998-10-01 00:00:00'),
 Timestamp('2043-07-01 00:00:00'),
 Timestamp('2034-12-31 00:00:00'),
 Timestamp('1993-01-01 00:00:00'),
 Timestamp('2009-01-11 00:00:00'),
 Timestamp('1999-09-04 00:00:00'),
 Timestamp('2008-04-20 00:00:00'),
 Timestamp('2015-08-29 00:00:00'),
 Timestamp('2004-03-31 00:00:00'),
 Timestamp('1992-01-29 00:00:00'),
 Timestamp('2055-02-01 00:00:00'),
 Timestamp('2007-09-03 00:00:00'),
 Timestamp('2006-09-03 00:00:00'),
 Timestamp('2001-09-30 00:00:00'),
 Timestamp('2012-11-04 00:00:00'),
 Timestamp('2009-06-02 00:00:00'),
 Timestamp('2063-12-22 00:00:00'),
 Timestamp('1937-01-01 00:00:00'),
 Timestamp('1944-01-01 00:00:00'),
 Timestamp('1982-02-14 00:00:00'),
 Timestamp('2060-06-27 00:00:00'),
 Timestamp('1987-01-01 00:00:00'),
 Timestamp('2011-08-24 00:00:00'),
 Timestamp('1992-07-08 00:00:00'),
 Timestamp('2002-05-22 00:00:00'),
 Timestamp('1993-06-11 00:00:00'),
 Timestamp('2014-10-05 00:00:00'),
 Timestamp('2006-01-01 00:00:00'),
 Timestamp('2011-09-17 00:00:00'),
 Timestamp('2004-06-26 00:00:00'),
 Timestamp('2002-03-15 00:00:00'),
 Timestamp('2000-07-15 00:00:00'),
 Timestamp('2044-10-26 00:00:00'),
 Timestamp('2007-08-09 00:00:00'),
 Timestamp('2013-08-31 00:00:00'),
 Timestamp('1920-01-01 00:00:00'),
 Timestamp('2008-07-25 00:00:00'),
 Timestamp('1999-10-30 00:00:00'),
 Timestamp('1991-06-07 00:00:00'),
 Timestamp('2061-04-16 00:00:00'),
 Timestamp('2001-09-15 00:00:00'),
 Timestamp('2015-05-29 00:00:00'),
 Timestamp('2049-08-28 00:00:00'),
 Timestamp('2000-05-07 00:00:00'),
 Timestamp('1995-08-26 00:00:00'),
 Timestamp('1853-01-01 00:00:00'),
 Timestamp('2056-09-01 00:00:00'),
 Timestamp('2013-08-25 00:00:00'),
 Timestamp('2013-05-27 00:00:00'),
 Timestamp('2055-08-01 00:00:00'),
 Timestamp('2008-05-10 00:00:00'),
 Timestamp('2007-12-21 00:00:00'),
 Timestamp('1998-11-02 00:00:00'),
 Timestamp('2002-06-13 00:00:00'),
 Timestamp('2014-11-08 00:00:00'),
 Timestamp('2059-12-19 00:00:00'),
 Timestamp('1971-04-05 00:00:00'),
 Timestamp('2010-08-10 00:00:00'),
 Timestamp('1987-03-30 00:00:00'),
 Timestamp('1878-01-01 00:00:00'),
 Timestamp('2065-11-21 00:00:00'),
 Timestamp('2011-03-21 00:00:00'),
 Timestamp('2035-01-24 00:00:00'),
 Timestamp('2007-06-30 00:00:00'),
 Timestamp('2002-06-09 00:00:00'),
 Timestamp('2059-06-14 00:00:00'),
 Timestamp('2058-07-27 00:00:00'),
 Timestamp('2015-11-15 00:00:00'),
 Timestamp('1996-09-02 00:00:00'),
 Timestamp('1920-01-24 00:00:00'),
 Timestamp('1998-05-29 00:00:00'),
 Timestamp('1970-01-01 00:00:00'),
 Timestamp('2059-08-15 00:00:00'),
 Timestamp('2015-11-01 00:00:00'),
 Timestamp('2014-10-17 00:00:00'),
 Timestamp('2011-08-16 00:00:00'),
 Timestamp('2016-07-26 00:00:00'),
 Timestamp('2013-02-21 00:00:00'),
 Timestamp('1996-10-03 00:00:00'),
 Timestamp('2004-10-09 00:00:00'),
 Timestamp('1995-08-22 00:00:00'),
 Timestamp('1972-10-21 00:00:00'),
 Timestamp('1989-09-09 00:00:00'),
 Timestamp('2057-04-07 00:00:00'),
 Timestamp('2009-07-22 00:00:00'),
 Timestamp('1986-09-01 00:00:00'),
 Timestamp('2003-11-06 00:00:00'),
 Timestamp('1977-12-19 00:00:00'),
 Timestamp('2010-06-25 00:00:00'),
 Timestamp('1991-04-16 00:00:00'),
 Timestamp('2015-11-10 00:00:00'),
 Timestamp('2013-07-29 00:00:00'),
 Timestamp('2004-06-10 00:00:00'),
 Timestamp('1988-06-16 00:00:00'),
 Timestamp('1981-08-10 00:00:00'),
 Timestamp('2010-10-02 00:00:00'),
 Timestamp('1981-10-19 00:00:00'),
 Timestamp('1842-01-01 00:00:00'),
 Timestamp('2061-09-24 00:00:00'),
 Timestamp('2015-07-23 00:00:00'),
 Timestamp('1901-01-01 00:00:00'),
 Timestamp('2006-08-22 00:00:00'),
 Timestamp('1915-07-06 00:00:00'),
 Timestamp('2042-11-13 00:00:00'),
 Timestamp('1988-04-15 00:00:00'),
 Timestamp('1993-08-19 00:00:00'),
 Timestamp('2015-06-27 00:00:00'),
 Timestamp('2062-08-01 00:00:00'),
 Timestamp('1994-05-31 00:00:00'),
 Timestamp('1984-07-01 00:00:00'),
 Timestamp('2002-01-01 00:00:00'),
 Timestamp('2015-03-29 00:00:00'),
 Timestamp('2004-07-02 00:00:00'),
 Timestamp('2009-12-18 00:00:00'),
 Timestamp('2043-05-17 00:00:00'),
 Timestamp('2014-12-29 00:00:00'),
 Timestamp('1936-01-01 00:00:00'),
 Timestamp('2062-01-07 00:00:00'),
 Timestamp('2059-09-26 00:00:00'),
 Timestamp('2016-04-07 00:00:00'),
 Timestamp('2010-09-03 00:00:00'),
 Timestamp('2064-07-08 00:00:00'),
 Timestamp('2015-06-25 00:00:00'),
 Timestamp('2003-11-30 00:00:00'),
 Timestamp('2010-11-30 00:00:00'),
 Timestamp('2015-07-26 00:00:00'),
 Timestamp('2009-12-20 00:00:00'),
 Timestamp('2046-01-24 00:00:00'),
 Timestamp('2062-03-25 00:00:00'),
 Timestamp('2047-11-08 00:00:00'),
 Timestamp('2062-08-30 00:00:00'),
 Timestamp('2014-04-12 00:00:00'),
 Timestamp('2008-05-24 00:00:00'),
 Timestamp('2011-09-20 00:00:00'),
 Timestamp('2016-05-21 00:00:00'),
 Timestamp('1983-06-15 00:00:00'),
 Timestamp('2031-09-21 00:00:00'),
 Timestamp('2000-08-21 00:00:00'),
 Timestamp('1987-07-12 00:00:00'),
 Timestamp('1972-10-14 00:00:00'),
 Timestamp('2061-12-18 00:00:00'),
 Timestamp('1893-06-22 00:00:00'),
 Timestamp('2009-12-05 00:00:00'),
 Timestamp('1998-07-06 00:00:00'),
 Timestamp('2009-02-07 00:00:00'),
 Timestamp('1997-08-02 00:00:00'),
 Timestamp('2064-02-14 00:00:00'),
 Timestamp('1860-04-01 00:00:00'),
 Timestamp('2055-03-01 00:00:00'),
 Timestamp('2009-03-01 00:00:00'),
 Timestamp('1882-01-01 00:00:00'),
 Timestamp('1978-01-01 00:00:00'),
 Timestamp('1976-09-12 00:00:00'),
 Timestamp('1993-09-16 00:00:00'),
 Timestamp('2013-09-29 00:00:00'),
 Timestamp('2066-12-27 00:00:00'),
 Timestamp('1996-12-01 00:00:00'),
 Timestamp('2015-01-01 00:00:00'),
 Timestamp('2003-12-13 00:00:00'),
 Timestamp('1983-01-01 00:00:00'),
 Timestamp('2007-02-03 00:00:00'),
 Timestamp('2001-04-08 00:00:00'),
 Timestamp('2016-02-10 00:00:00'),
 Timestamp('1995-06-17 00:00:00'),
 Timestamp('1983-08-13 00:00:00'),
 Timestamp('1992-06-28 00:00:00'),
 Timestamp('2037-10-27 00:00:00'),
 Timestamp('1880-05-02 00:00:00'),
 Timestamp('1877-12-15 00:00:00'),
 Timestamp('2006-08-29 00:00:00'),
 Timestamp('2014-10-02 00:00:00'),
 Timestamp('2063-06-01 00:00:00'),
 Timestamp('2007-09-16 00:00:00'),
 Timestamp('1997-12-25 00:00:00'),
 Timestamp('2061-01-03 00:00:00'),
 Timestamp('2000-06-09 00:00:00'),
 Timestamp('2002-07-10 00:00:00'),
 Timestamp('2015-06-14 00:00:00'),
 Timestamp('1982-06-26 00:00:00'),
 Timestamp('2064-02-05 00:00:00'),
 Timestamp('2011-07-13 00:00:00'),
 Timestamp('2008-09-28 00:00:00'),
 Timestamp('2007-08-28 00:00:00'),
 Timestamp('1976-03-12 00:00:00'),
 Timestamp('2010-10-23 00:00:00'),
 Timestamp('2014-08-02 00:00:00'),
 Timestamp('2016-07-28 00:00:00'),
 Timestamp('2002-05-21 00:00:00'),
 Timestamp('2006-07-09 00:00:00'),
 Timestamp('2012-10-18 00:00:00'),
 Timestamp('1975-01-01 00:00:00'),
 Timestamp('2035-07-27 00:00:00'),
 Timestamp('1972-06-26 00:00:00'),
 Timestamp('1981-09-03 00:00:00'),
 Timestamp('2009-05-16 00:00:00'),
 Timestamp('2063-11-30 00:00:00'),
 Timestamp('2009-07-11 00:00:00'),
 Timestamp('1998-08-01 00:00:00'),
 Timestamp('2008-11-09 00:00:00'),
 Timestamp('1979-05-01 00:00:00'),
 Timestamp('1887-02-08 00:00:00'),
 Timestamp('1907-10-16 00:00:00'),
 Timestamp('2011-07-07 00:00:00'),
 Timestamp('2062-06-10 00:00:00'),
 Timestamp('2016-01-24 00:00:00'),
 Timestamp('2009-03-19 00:00:00'),
 Timestamp('2006-12-06 00:00:00'),
 Timestamp('2050-04-09 00:00:00'),
 Timestamp('1874-06-15 00:00:00'),
 Timestamp('1995-08-31 00:00:00'),
 Timestamp('2049-12-01 00:00:00'),
 Timestamp('2004-11-11 00:00:00'),
 Timestamp('2012-03-06 00:00:00'),
 Timestamp('2011-09-04 00:00:00'),
 Timestamp('2055-08-30 00:00:00'),
 Timestamp('2015-07-04 00:00:00'),
 Timestamp('1985-09-08 00:00:00'),
 Timestamp('2005-03-25 00:00:00'),
 Timestamp('2016-07-06 00:00:00'),
 Timestamp('1995-09-30 00:00:00'),
 Timestamp('2011-09-24 00:00:00'),
 Timestamp('2011-01-01 00:00:00'),
 Timestamp('2012-07-30 00:00:00'),
 Timestamp('2004-05-23 00:00:00'),
 Timestamp('2004-03-27 00:00:00'),
 Timestamp('2065-10-16 00:00:00'),
 Timestamp('2010-07-17 00:00:00'),
 Timestamp('2016-06-21 00:00:00'),
 Timestamp('2001-09-07 00:00:00'),
 Timestamp('2016-06-23 00:00:00'),
 Timestamp('2008-08-24 00:00:00'),
 Timestamp('2008-04-08 00:00:00'),
 Timestamp('2011-09-11 00:00:00'),
 Timestamp('2064-03-28 00:00:00'),
 Timestamp('2013-04-02 00:00:00'),
 Timestamp('1983-08-20 00:00:00'),
 Timestamp('2008-09-06 00:00:00'),
 Timestamp('2002-09-21 00:00:00'),
 Timestamp('1973-12-18 00:00:00'),
 Timestamp('2023-01-27 00:00:00'),
 Timestamp('1989-01-26 00:00:00'),
 Timestamp('1999-11-01 00:00:00'),
 Timestamp('1993-06-01 00:00:00'),
 Timestamp('1913-08-27 00:00:00'),
 Timestamp('2000-09-16 00:00:00'),
 Timestamp('1909-01-01 00:00:00'),
 Timestamp('2004-07-28 00:00:00'),
 Timestamp('1886-01-01 00:00:00'),
 Timestamp('2004-04-13 00:00:00'),
 Timestamp('2003-11-12 00:00:00'),
 Timestamp('2013-06-06 00:00:00'),
 Timestamp('2006-07-31 00:00:00'),
 Timestamp('1982-07-01 00:00:00'),
 Timestamp('2000-10-06 00:00:00'),
 Timestamp('2009-01-10 00:00:00'),
 Timestamp('2046-07-18 00:00:00'),
 Timestamp('1993-08-01 00:00:00'),
 Timestamp('1991-11-26 00:00:00'),
 Timestamp('2054-01-22 00:00:00'),
 Timestamp('1974-02-13 00:00:00'),
 Timestamp('1981-12-13 00:00:00'),
 Timestamp('2007-01-25 00:00:00'),
 Timestamp('1978-06-21 00:00:00'),
 Timestamp('2012-07-23 00:00:00'),
 Timestamp('2007-07-18 00:00:00'),
 Timestamp('2008-04-26 00:00:00'),
 Timestamp('2008-04-28 00:00:00'),
 Timestamp('1974-09-01 00:00:00'),
 Timestamp('2002-03-25 00:00:00'),
 Timestamp('2011-05-13 00:00:00'),
 Timestamp('2033-08-28 00:00:00'),
 Timestamp('2010-01-22 00:00:00'),
 Timestamp('2055-09-23 00:00:00'),
 Timestamp('2010-10-28 00:00:00'),
 Timestamp('1984-09-22 00:00:00'),
 Timestamp('2001-09-03 00:00:00'),
 Timestamp('2005-07-15 00:00:00'),
 Timestamp('1910-01-01 00:00:00'),
 Timestamp('2007-09-27 00:00:00'),
 Timestamp('1874-07-15 00:00:00'),
 Timestamp('2005-09-02 00:00:00'),
 Timestamp('2006-07-08 00:00:00'),
 Timestamp('1983-11-10 00:00:00'),
 Timestamp('2014-07-05 00:00:00'),
 Timestamp('2016-06-02 00:00:00'),
 Timestamp('1906-09-27 00:00:00'),
 Timestamp('1975-06-23 00:00:00'),
 Timestamp('2066-08-23 00:00:00'),
 Timestamp('2011-12-07 00:00:00'),
 Timestamp('2065-04-04 00:00:00'),
 Timestamp('2060-12-27 00:00:00'),
 Timestamp('2059-07-25 00:00:00'),
 Timestamp('2010-08-07 00:00:00'),
 Timestamp('1988-08-22 00:00:00'),
 Timestamp('2009-11-16 00:00:00'),
 Timestamp('2054-10-02 00:00:00'),
 Timestamp('2053-04-01 00:00:00'),
 Timestamp('2003-09-13 00:00:00'),
 Timestamp('1878-09-02 00:00:00'),
 Timestamp('2059-07-23 00:00:00'),
 Timestamp('1997-12-28 00:00:00'),
 Timestamp('1983-04-02 00:00:00'),
 Timestamp('2032-08-30 00:00:00'),
 Timestamp('1897-01-01 00:00:00'),
 Timestamp('1990-10-30 00:00:00'),
 Timestamp('1827-06-01 00:00:00'),
 Timestamp('2061-02-17 00:00:00'),
 Timestamp('2003-07-05 00:00:00'),
 Timestamp('2048-09-19 00:00:00'),
 Timestamp('1980-01-01 00:00:00'),
 Timestamp('2013-05-23 00:00:00'),
 Timestamp('2016-08-29 00:00:00'),
 Timestamp('2015-08-22 00:00:00'),
 Timestamp('2006-07-17 00:00:00'),
 Timestamp('2007-05-07 00:00:00'),
 Timestamp('2042-09-12 00:00:00'),
 Timestamp('2010-07-02 00:00:00'),
 Timestamp('1931-01-01 00:00:00'),
 Timestamp('1988-04-14 00:00:00'),
 Timestamp('2061-10-01 00:00:00'),
 Timestamp('2066-05-16 00:00:00'),
 Timestamp('2005-05-02 00:00:00'),
 Timestamp('2010-08-02 00:00:00'),
 Timestamp('2003-04-23 00:00:00'),
 Timestamp('2011-12-21 00:00:00'),
 Timestamp('2060-04-03 00:00:00'),
 Timestamp('2005-08-24 00:00:00'),
 Timestamp('1984-06-03 00:00:00'),
 Timestamp('1985-07-25 00:00:00'),
 Timestamp('2011-06-19 00:00:00'),
 Timestamp('2065-06-01 00:00:00'),
 Timestamp('2016-09-05 00:00:00'),
 Timestamp('1999-08-05 00:00:00'),
 Timestamp('1978-04-02 00:00:00'),
 Timestamp('1989-01-01 00:00:00'),
 Timestamp('1995-11-25 00:00:00'),
 Timestamp('2012-09-06 00:00:00'),
 Timestamp('1907-08-12 00:00:00'),
 Timestamp('1995-09-03 00:00:00'),
 Timestamp('2016-07-16 00:00:00'),
 Timestamp('2014-04-04 00:00:00'),
 Timestamp('2054-08-12 00:00:00'),
 Timestamp('2014-03-22 00:00:00'),
 Timestamp('2011-08-28 00:00:00'),
 Timestamp('2064-12-10 00:00:00'),
 Timestamp('2004-10-30 00:00:00'),
 Timestamp('2059-08-14 00:00:00'),
 Timestamp('2051-08-17 00:00:00'),

In [33]:
# Check how many could not be converted.

df["Date"].isnull().sum()

272

In [34]:
# Drop year column, as it overlaps with Date column

df = df.drop(columns="Year")

In [35]:
# Check type column.

df["Type"].value_counts()

Unprovoked      4385
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: Type, dtype: int64

In [36]:
# Merge Boat and Boating to Boat Type Attacks. Other types seem ok

df.loc[df["Type"] == "Boating", ["Type"]] = "Boat"

In [37]:
## Next, look at country, area and location

list(df["Country"].value_counts().index)

['USA',
 'AUSTRALIA',
 'SOUTH AFRICA',
 'PAPUA NEW GUINEA',
 'NEW ZEALAND',
 'BRAZIL',
 'BAHAMAS',
 'MEXICO',
 'ITALY',
 'FIJI',
 'PHILIPPINES',
 'REUNION',
 'NEW CALEDONIA',
 'MOZAMBIQUE',
 'CUBA',
 'SPAIN',
 'INDIA',
 'EGYPT',
 'CROATIA',
 'JAPAN',
 'PANAMA',
 'SOLOMON ISLANDS',
 'IRAN',
 'GREECE',
 'HONG KONG',
 'JAMAICA',
 'FRENCH POLYNESIA',
 'INDONESIA',
 'ENGLAND',
 'PACIFIC OCEAN',
 'ATLANTIC OCEAN',
 'BERMUDA',
 'TONGA',
 'VANUATU',
 'VIETNAM',
 'MARSHALL ISLANDS',
 'SRI LANKA',
 'FRANCE',
 'TURKEY',
 'IRAQ',
 'SOUTH ATLANTIC OCEAN',
 'COSTA RICA',
 'SENEGAL',
 'VENEZUELA',
 'CANADA',
 'UNITED KINGDOM',
 'NEW GUINEA',
 'KENYA',
 'COLUMBIA',
 'TAIWAN',
 'SOUTH KOREA',
 'SCOTLAND',
 'ECUADOR',
 'SIERRA LEONE',
 'TANZANIA',
 'CARIBBEAN SEA',
 'CHILE',
 'DOMINICAN REPUBLIC',
 'NORTH PACIFIC OCEAN',
 'YEMEN ',
 'ISRAEL',
 'INDIAN OCEAN',
 'SAMOA',
 'MAURITIUS',
 'MADAGASCAR',
 'SEYCHELLES',
 'NICARAGUA',
 'KIRIBATI',
 'SOMALIA',
 'SINGAPORE',
 'CHINA',
 'THAILAND',
 'NEW BRITAIN',
 'OKINAWA',
 'AZORES',
 'PALAU',
 'MID ATLANTIC OCEAN',
 'TURKS & CAICOS',
 'SAUDI ARABIA',
 'BARBADOS',
 'MALTA',
 'LIBYA',
 'GRENADA',
 'NIGERIA',
 'RUSSIA',
 'GUAM',
 'SUDAN',
 'PERSIAN GULF',
 'BURMA',
 'EL SALVADOR',
 'NORTH ATLANTIC OCEAN',
 'MALAYSIA',
 'URUGUAY',
 'BELIZE',
 'GUINEA',
 'AMERICAN SAMOA',
 ' TONGA',
 'CAPE VERDE',
 'MICRONESIA',
 'LIBERIA',
 'MONTENEGRO',
 'Fiji',
 'LEBANON',
 'TUNISIA',
 'HONDURAS',
 'HAITI',
 'PORTUGAL',
 'TRINIDAD & TOBAGO',
 'CAYMAN ISLANDS',
 'MEDITERRANEAN SEA',
 'PACIFIC OCEAN ',
 'SOUTHWEST PACIFIC OCEAN',
 'NORWAY',
 'UNITED ARAB EMIRATES (UAE)',
 'CENTRAL PACIFIC',
 'NAMIBIA',
 'YEMEN',
 'SOUTH PACIFIC OCEAN',
 'JOHNSTON ISLAND',
 'EGYPT ',
 'CRETE',
 'COOK ISLANDS',
 ' PHILIPPINES',
 'St Helena',
 'Seychelles',
 'GUYANA',
 'MAYOTTE',
 'ADMIRALTY ISLANDS',
 'NORTHERN ARABIAN SEA',
 'GULF OF ADEN',
 'EQUATORIAL GUINEA / CAMEROON',
 'BRITISH NEW GUINEA',
 'ANTIGUA',
 'MEDITERRANEAN SEA?',
 'RED SEA / INDIAN OCEAN',
 'Coast of AFRICA',
 'SOLOMON ISLANDS / VANUATU',
 'RED SEA',
 'JAVA',
 'NEVIS',
 'IRELAND',
 'BRITISH ISLES',
 'ST. MAARTIN',
 'SLOVENIA',
 'THE BALKANS',
 'NORTH SEA',
 'KUWAIT',
 'GRAND CAYMAN',
 'IRAN / IRAQ',
 'BANGLADESH',
 'TUVALU',
 'ARGENTINA',
 'FALKLAND ISLANDS',
 'RED SEA?',
 'SWEDEN',
 'CURACAO',
 'MEXICO ',
 'NETHERLANDS ANTILLES',
 'MALDIVE ISLANDS',
 'DJIBOUTI',
 'ALGERIA',
 'GEORGIA',
 'SUDAN?',
 'MID-PACIFC OCEAN',
 'ASIA?',
 'Between PORTUGAL & INDIA',
 'TASMAN SEA',
 'INDIAN OCEAN?',
 'BRITISH VIRGIN ISLANDS',
 'PARAGUAY',
 'SYRIA',
 'MARTINIQUE',
 'NICARAGUA ',
 'BAHREIN',
 'NORTHERN MARIANA ISLANDS',
 'SAN DOMINGO',
 'PUERTO RICO',
 'GREENLAND',
 'WESTERN SAMOA',
 'NORTH ATLANTIC OCEAN ',
 'ANDAMAN / NICOBAR ISLANDAS',
 'GHANA',
 'ST. MARTIN',
 'FEDERATED STATES OF MICRONESIA',
 'KOREA',
 'BRITISH WEST INDIES',
 'ITALY / CROATIA',
 'GUATEMALA',
 'GABON',
 'PALESTINIAN TERRITORIES',
 'EGYPT / ISRAEL',
 'Sierra Leone',
 'CEYLON (SRI LANKA)',
 'BAY OF BENGAL',
 'CYPRUS',
 'MONACO',
 'SOUTH CHINA SEA',
 'OCEAN',
 'ICELAND',
 'ARUBA',
 'DIEGO GARCIA',
 'UNITED ARAB EMIRATES',
 'ANGOLA']

In [38]:
## Country: Uppercase all, remove question marks, remove whitespace at beginning and end

df['Country'] = df['Country'].str.upper() 
df['Country'] = df['Country'].str.replace("?","")
df['Country'] = df['Country'].str.lstrip().str.rstrip()

In [39]:
list(df["Country"].value_counts().index)

['USA',
 'AUSTRALIA',
 'SOUTH AFRICA',
 'PAPUA NEW GUINEA',
 'NEW ZEALAND',
 'BRAZIL',
 'BAHAMAS',
 'MEXICO',
 'ITALY',
 'FIJI',
 'PHILIPPINES',
 'REUNION',
 'NEW CALEDONIA',
 'MOZAMBIQUE',
 'CUBA',
 'SPAIN',
 'EGYPT',
 'INDIA',
 'CROATIA',
 'PANAMA',
 'JAPAN',
 'IRAN',
 'SOLOMON ISLANDS',
 'GREECE',
 'HONG KONG',
 'JAMAICA',
 'FRENCH POLYNESIA',
 'INDONESIA',
 'PACIFIC OCEAN',
 'ENGLAND',
 'TONGA',
 'ATLANTIC OCEAN',
 'BERMUDA',
 'VIETNAM',
 'VANUATU',
 'SRI LANKA',
 'MARSHALL ISLANDS',
 'FRANCE',
 'COSTA RICA',
 'IRAQ',
 'TURKEY',
 'SOUTH ATLANTIC OCEAN',
 'VENEZUELA',
 'SENEGAL',
 'CANADA',
 'KENYA',
 'UNITED KINGDOM',
 'NEW GUINEA',
 'YEMEN',
 'SIERRA LEONE',
 'COLUMBIA',
 'TAIWAN',
 'SOUTH KOREA',
 'ECUADOR',
 'SCOTLAND',
 'SEYCHELLES',
 'TANZANIA',
 'CARIBBEAN SEA',
 'INDIAN OCEAN',
 'CHILE',
 'DOMINICAN REPUBLIC',
 'MADAGASCAR',
 'SAMOA',
 'MAURITIUS',
 'NICARAGUA',
 'NORTH PACIFIC OCEAN',
 'ISRAEL',
 'THAILAND',
 'KIRIBATI',
 'CHINA',
 'SOMALIA',
 'NEW BRITAIN',
 'OKINAWA',
 'SINGAPORE',
 'SUDAN',
 'LIBYA',
 'NORTH ATLANTIC OCEAN',
 'PALAU',
 'SAUDI ARABIA',
 'TURKS & CAICOS',
 'MID ATLANTIC OCEAN',
 'AZORES',
 'BARBADOS',
 'MALTA',
 'MALAYSIA',
 'BURMA',
 'NIGERIA',
 'GRENADA',
 'EL SALVADOR',
 'GUAM',
 'PERSIAN GULF',
 'RUSSIA',
 'URUGUAY',
 'LIBERIA',
 'MEDITERRANEAN SEA',
 'MONTENEGRO',
 'HONDURAS',
 'AMERICAN SAMOA',
 'TRINIDAD & TOBAGO',
 'PORTUGAL',
 'TUNISIA',
 'MICRONESIA',
 'BELIZE',
 'HAITI',
 'CAPE VERDE',
 'GUINEA',
 'LEBANON',
 'JOHNSTON ISLAND',
 'SOUTHWEST PACIFIC OCEAN',
 'SOUTH PACIFIC OCEAN',
 'CRETE',
 'CAYMAN ISLANDS',
 'CENTRAL PACIFIC',
 'NAMIBIA',
 'NORWAY',
 'UNITED ARAB EMIRATES (UAE)',
 'RED SEA',
 'ADMIRALTY ISLANDS',
 'GULF OF ADEN',
 'COOK ISLANDS',
 'ST. MAARTIN',
 'BRITISH ISLES',
 'JAVA',
 'GUYANA',
 'RED SEA / INDIAN OCEAN',
 'NEVIS',
 'COAST OF AFRICA',
 'EQUATORIAL GUINEA / CAMEROON',
 'SLOVENIA',
 'NORTHERN ARABIAN SEA',
 'BRITISH NEW GUINEA',
 'ANTIGUA',
 'NORTH SEA',
 'MAYOTTE',
 'THE BALKANS',
 'KUWAIT',
 'SOLOMON ISLANDS / VANUATU',
 'IRELAND',
 'BRITISH WEST INDIES',
 'KOREA',
 'GREENLAND',
 'IRAN / IRAQ',
 'GEORGIA',
 'ANGOLA',
 'SAN DOMINGO',
 'ASIA',
 'NORTHERN MARIANA ISLANDS',
 'TUVALU',
 'SYRIA',
 'SWEDEN',
 'CURACAO',
 'NETHERLANDS ANTILLES',
 'GRAND CAYMAN',
 'DJIBOUTI',
 'ALGERIA',
 'ST HELENA',
 'BANGLADESH',
 'MID-PACIFC OCEAN',
 'BAHREIN',
 'TASMAN SEA',
 'BRITISH VIRGIN ISLANDS',
 'PARAGUAY',
 'MARTINIQUE',
 'ARUBA',
 'ICELAND',
 'SOUTH CHINA SEA',
 'GUATEMALA',
 'PUERTO RICO',
 'WESTERN SAMOA',
 'CEYLON (SRI LANKA)',
 'ANDAMAN / NICOBAR ISLANDAS',
 'GHANA',
 'ST. MARTIN',
 'FEDERATED STATES OF MICRONESIA',
 'BETWEEN PORTUGAL & INDIA',
 'ITALY / CROATIA',
 'GABON',
 'MONACO',
 'CYPRUS',
 'OCEAN',
 'PALESTINIAN TERRITORIES',
 'DIEGO GARCIA',
 'UNITED ARAB EMIRATES',
 'BAY OF BENGAL',
 'ARGENTINA',
 'FALKLAND ISLANDS',
 'MALDIVE ISLANDS',
 'EGYPT / ISRAEL']

In [40]:
# Area column: remove whitespaces at beginning and end, remove �, Capitalise all words



df['Area'] = df['Area'].str.title() 
df['Area'] = df['Area'].str.lstrip().str.rstrip()
df['Area'] = df['Area'].str.replace("�","")
df['Area'] = df['Area'].str.replace("?","")

In [41]:
list(df["Area"].value_counts().index)

['Florida',
 'New South Wales',
 'Queensland',
 'Hawaii',
 'California',
 'Kwazulu-Natal',
 'Western Cape Province',
 'Western Australia',
 'Eastern Cape Province',
 'South Carolina',
 'North Carolina',
 'South Australia',
 'Victoria',
 'Torres Strait',
 'Texas',
 'Pernambuco',
 'North Island',
 'New Jersey',
 'Tasmania',
 'South Island',
 'New York',
 'Oregon',
 'Northern Territory',
 'Central Province',
 'Abaco Islands',
 'Virginia',
 'Havana Province',
 'South Province',
 'Veracruz',
 'Puerto Rico',
 'Gaza',
 'New Ireland Province',
 'Madang Province',
 'Alabama',
 'Khuzestan Province',
 'Georgia',
 'Guerrero',
 'Primorje-Gorski Kotar County',
 'North Province',
 'Quintana Roo',
 'Adriatic Sea',
 'Luzon Island',
 'Tyrrhenian Sea',
 'Mediterranean Sea',
 'Louisiana',
 'Rio De Janeiro',
 'Massachusetts',
 'Malampa Province',
 'Grand Bahama Island',
 'Baja California',
 'Red Sea',
 'Basrah',
 'Society Islands',
 'Bougainville (North Solomons)',
 'Eastern Province',
 'Morobe Province',
 'West Bengal',
 'Viti Levu Island',
 'Maputo Province',
 'Milne Bay Province',
 'New Britain',
 'Admiralty Islands, Manus Province',
 'Kingston Parish',
 'Binh Dinh Province',
 'Tamil Nadu',
 'Sicily',
 'Mirs Bay',
 'West New Britain Province',
 'Loyalty Islands',
 'South Sinai Peninsula',
 'Aden',
 'Caribbean Sea',
 'Western Area',
 'Canary Islands',
 'Maryland',
 'Karun River',
 'Delaware',
 'Rhode Island',
 'Andros Islands',
 'New Providence Island',
 'Hamilton',
 'Shatt-Al-Arab River',
 'Inhambane Province',
 'Coast Province',
 'Tuamotus',
 'Ehime Prefecture',
 'Connecticut',
 'Guantanamo Province',
 'Cap Vert Peninsula',
 'Galapagos Islands',
 'Bimini Islands',
 'Saint-Paul',
 'Tamaulipas',
 'MaranhO',
 'Mississippi',
 'Bali',
 'Western Province',
 'Us Virgin Islands',
 'Exuma Islands',
 'Madang',
 'Limpopo River',
 "Vava'U",
 'Taveuni',
 'Cook Islands',
 'New Ireland Province, Bismarck Archipelago',
 'La Libertad',
 'Zadar County',
 '22N, 88E',
 'Saint-Denis',
 'Vita Levu',
 'Guerro',
 'Catalonia',
 'Sinai Peninsula',
 'Tuscany',
 'Banaadir Region',
 'Eleuthera',
 'Vanua Levu',
 'Saint-Gilles',
 'New Territories',
 'Liguria',
 'Sardinia',
 'Guerrrero',
 'Abau Sub District, Central Province',
 'Valencia',
 'Tutuila Island',
 'Westmoreland Parish',
 'Western Caroline Islands',
 'Calabria',
 'Corfu',
 'Java',
 "Grand'Anse",
 'Saint-Pierre',
 'CDiz',
 'Istria County',
 'VavaU',
 'Viti Levu',
 'Corfu Island',
 'Northern Taiwan',
 'Split-Dalmatia Count,',
 'Hong Kong',
 'Zamboanga Del Sur Province',
 'Lake Nicaragua (Fresh Water)',
 'Red Sea State',
 'Cornwall',
 'Manila',
 'Alicante',
 'Eniwetok Atoll',
 'Isle Of Wight',
 'Santiago De Cuba Province',
 'Yasawa Islands',
 'Rocha',
 'Nova Scotia',
 'Saint-Gilles-Les-Bains',
 'Guadalcanal Province',
 'Mombasa',
 'Okayama Prefecture',
 'Sinaloa',
 'Devon',
 "CTe D'Azur",
 'Upolu Island',
 'Vitu Levu',
 'Bahia',
 'St. Andrew Parish',
 'Louisiade Archipelago',
 'Colima',
 'St. Johns Reef',
 'Trinidad',
 'Gulf Of Panama',
 'Near Puntarenas',
 'Hoogly River',
 'Chatham Islands',
 'Tongapatu Group',
 'Off The Coast Of West Africa',
 'Saint-Joseph',
 'LimN Province',
 'Taitung',
 'Berry Islands',
 "Ha'Api",
 'English Channel',
 'Saint-BenoT',
 'Makira-Ulawa Province',
 'Gilbert Islands',
 'Miyako',
 'Guanacaste',
 'San Blas Islands',
 'St Michael Parish',
 'DTang-Sal',
 'Honiara',
 'Palmyra Atoll',
 'Saint-Leu',
 'East New Britain Province',
 'Cheshire',
 'Southland',
 'Colon Province',
 '1000 Miles West Of Hawaii',
 'Rio Grande De Norte',
 'Rangoon',
 'Anzoategui',
 'Ligurian Sea',
 'Out Islands',
 'Vera Cruz',
 'Nueva Esparta',
 'Montserrado',
 'Lau Group',
 'ColN Province',
 'Canal Zone',
 'Phoenix Islands',
 'Grand Terre',
 'Saint-Benoit',
 'Alinglaplap Atoll',
 'Gulf Province',
 'Luzon',
 'Eastern Caroline Islands',
 'Paget',
 'Maharashtra',
 'Dorset',
 'Saint-Philippe',
 'Cat Cay',
 'Matanzas Province (North Coast)',
 'Split-Dalmatia County',
 'East Java',
 'Wakayama Prefecture',
 'Praslin',
 'West End',
 'Eastern  Province',
 'Duke Of York Islands',
 'Ralik Archipelago',
 'Malaga',
 'Kadavu',
 'Venice Province',
 'Villa Clara Province',
 'Between Hawaii & Wake Island',
 'Sussex',
 'New Georgia',
 'Oaxaca',
 'Off Libya',
 'East Sepik',
 'Caicos Bank',
 'Inhambe Province',
 'Bora Bora',
 'Grand Canary Island',
 'Sea Of Japan',
 'Palawan',
 'Newfoundland',
 'Camaguey Province',
 'Dodecanese Islands',
 "Nuku'Alofa",
 'Miyako Island',
 'Orissa',
 'Ionian Sea',
 'Great Exuma Island',
 'New Ireland',
 'Lomaloma, Lau',
 'Between Hastings & Fairlight, Sussex',
 'Sucre',
 'Istria',
 'Inner Islands',
 'Trois-Bassins',
 'Mount Lebanon',
 'Rayong Province',
 'Southern Thailand',
 'Kent',
 'Leyte Island',
 'Santa Elena',
 'Socotra Islands',
 'Northern Java',
 'Negros',
 'Off Coast Of West Africa',
 'Attica',
 'Western Caroline Islands (North Pacific Ocean)',
 'Port Louis Province',
 '150 Miles Offshore',
 'South Sinai, Gulf Of Aqaba',
 'West Coast',
 'Nagasaki Prefecture',
 'Chungnam',
 'Ba Ria-Vung Tau  Province',
 'Southern Province',
 'Sandaun Province',
 'East Coast',
 'Carpathian Sea',
 'Anatolia',
 'Cavite Province, Luzon',
 'Providenciales',
 'Eastern Catalona',
 'Near Dakar, Cap Vert Peninsula',
 'Bocas',
 'Guyamas',
 'Sago Prefecture',
 'Lomaiviti  Island Group',
 'Pacific Coast',
 'Florida Straits',
 '33N, 68W',
 'Buenos Aires Province',
 'Manfredonia',
 'Los Vilos',
 'Bois-Blanc',
 '300 Miles From Antigua',
 '165  Miles From Bermuda',
 'Las Perlas Archipelago',
 'French Southern Territories',
 '"Head Of The Gulf"',
 'Caribbean Coast',
 '180 Miles Southeast Of Okinawa',
 'Mugla Province',
 'Manila Bay',
 'Atsumi Peninsula',
 'Toamasina Province',
 'Fujairah Emirate',
 'Bay Islands',
 'Between Honiara & Isabel Island',
 'Madeira',
 'Saint Gilles',
 'St. Thomas Bay',
 'Mindoro Occidental',
 'Cap-Vert Peninsula',
 '800 Miles From Land',
 'San Carlos',
 'North & South Carolina',
 'Bocas Del Toro',
 'Antalya Province',
 'Muala',
 'Norfolk',
 '(Southwestern Pacific)',
 'South Shore',
 'Shatt-El-Arab River',
 'Salerno Province',
 'Pacific Ocean',
 'Santa Catarina State',
 'West Of Ceylon (Sri  Lanka)',
 'Jeju Province',
 'Isla Provedencia',
 'South Island, Near Karitane North Of Dunedin',
 'Northlands',
 'Taipei Hsien',
 'Barlavento Islands',
 'Gulf Of Lyons',
 'Sainte-Marie',
 'Midway Atoll',
 'Madeira Islands',
 'Edinburgh',
 'Manus Island',
 'Bandar MaShur Sea Inlet',
 'Guam',
 'Somewhere Between Philadelphia And Hiogo, Japan',
 'Slovenia',
 'Conakry Region',
 'Thessaly',
 'Between Dr And Puerto Rico',
 '25 Km Off The Coast Of Iran & 483Km From Mouth Of Persian Gulf',
 "St. Mary'S Parish",
 'Aichi Prefecture',
 'Between Somalia & Yemen',
 'Off Thessaly',
 'Johnston Atoll',
 'Inner Hebrides',
 'Rio Grande Do Sul',
 'Cyclades Archipelago',
 'Cyrenaica',
 'Tel Aviv',
 'Genoa Province',
 'Kagoshima Prefecture',
 'San AndrS Archipelago',
 'Minerva Reef',
 '740 Miles Se Of Tarawa Atoll',
 'Antofagasta Province',
 '2 To 3 Miles Off Taboguilla Island, Pacific Ocean',
 'In The English Channel',
 'Pagasitikos Gulf',
 'South China Sea 200 Miles From Hong Kong',
 'Georges Bank',
 'Shanghai',
 'Western District',
 'Territory Of Cocos (Keeling) Islands',
 'Cay Sal Bank',
 'Viscayan Sea',
 'Sants-Montjic',
 'Mafia Island',
 'Arran',
 'Foveaux Strait',
 'Open Sea',
 'Rivers State',
 'Western Papuan Gulf',
 'Pennsylvania',
 'Moala Island',
 'Near The Andaman & Nicobar Islands',
 'Curacao',
 'Unknown, Treated At Wick, Scotland',
 'Near Bougainville (North Solomons)',
 'Marches Region',
 'Dubai',
 'Laucala Island',
 'Ancona Province',
 'Southwest Coast',
 'Off Green Island',
 'Wallis And Futuna',
 'Dar-Es-Salaam',
 'British Colombia',
 'Cienfuegos Province',
 'Sainte-Suzanne',
 'San Blas Coast',
 'Delagoa Bay',
 'Fernando Po Island',
 'Saint-Louis',
 'Munxar Reef',
 'East Wall',
 'Bernardino Strait Near Gulf Of Leyte',
 'Andikira Fokithes',
 'Kentucky',
 'In Convoy Ob 274',
 '12 Miles Off The North Coast',
 '19S, 178E',
 'Alicante Province',
 'New Mexico',
 'Altagracia Province',
 'Porto Seguro',
 'Grand Baie',
 'Ysabel Island',
 'Kuril Islands In The Pacific',
 'Lamu Archipelago',
 'Trelawney Province',
 "St John'S",
 'Milne Bay  Province',
 'On The Kowloon Penisula, South Of Sai Kung',
 'Lomaiviti Province',
 'Simpson Bay',
 'Le Port',
 'Kochi Prefecture',
 '04.05N-13.23W',
 'Ibaraki Prefecture',
 'Queaon',
 'Gibraltar',
 'St. Georges',
 'Tyrrenian Sea',
 'Off The Coromandel Peninsula, North Island',
 'Antarctic Ocean',
 'Galica',
 'Northern Peloponnese',
 '330 To 350 Miles East Of Wake Island',
 'Eastern Cape  Province',
 'Bay Of Maputu',
 'Primorsky Krai',
 'MLaga',
 'Provence',
 'United Arab Emirates',
 'Oslo Fjord',
 'Kikori River Mouth',
 'Kerala',
 'Saman Province',
 "250 Miles Southwest Of O'Ahu, Hawaii",
 'Merizo',
 'Cyclades',
 'Panama City',
 'Bay Of Maputo',
 'North Of Pernambuco, Brazil',
 'Syracuse',
 'Ralik Chain',
 'Rigo Subdistrict',
 'Riau Province',
 'Enroute From Suez To Aden (Yemen)',
 'Golfo De Venezia',
 'Peter The Great Bay, Khasan, Primorsky Krai (Far East)',
 'Northern Province',
 'Southern District',
 'Kwajalein Atoll',
 'Off The Coast Of South America',
 'Eronogo Region',
 'Leyte',
 'New Britain, Bismarck Archipelago',
 'Kagawa Prefecture',
 'Mersin Province',
 '30 Nm From Singapore',
 'St. Catherine',
 'Izo Islands',
 'Saint Leu',
 'Northern Bahamas',
 'Niua',
 'Western Viscayas',
 'Shat-Al-Arab River',
 'Casamance',
 'Bay Of Campeche',
 'Mercury Islands',
 'Grand Cayman',
 'Rombion Province',
 'Congreve Channel',
 'Piraeus',
 'Cikobia Island (North Of Vanua Levu)',
 'Naples Province',
 'Between Southampton & Canary Islands',
 'Lagos',
 'Northern District',
 'Trieste',
 'Mindanao',
 'Taranto Province',
 'Off Samar Island In The Gulf Of Leyte',
 'Off Cape Haitien',
 'Kadavu Island Group',
 'Galicia',
 'San Blas',
 'Island Of Volos',
 'Corregidor Island',
 'Viti Levu Group',
 'Tokyo Prefecture',
 'Camiguin Island',
 '300 Miles East Of Luzon',
 'Illeginni Atoll',
 'Green Bay',
 'Andaman Islands',
 'Magarita Or Cubagua Islands',
 'Washington',
 'Sanma Province',
 'Middle Caicos',
 'Clearwater Bay',
 'Batanes Provine',
 'Johor',
 'Between England & South Africa',
 '9.35N 79.35W',
 'Santo Domingo',
 'Paraiba',
 'Genoa  Province',
 'Cook Strait',
 'Demerara County',
 'Lucy',
 'Kumamoto Prefecture',
 'Moro Gulf',
 'Ambergris Caye',
 'Caroline Islands',
 'Taranto',
 'Alpes Maritime',
 'Surigao Del Norte',
 'Hokkaido Prefecture',
 'Nicoya Peninsula',
 '1,000 Miles East Of Hawaii',
 'Bird Island',
 'Black River',
 'Misamis Oriental',
 'ConservatRia District',
 'Between New Ireland & New Britain',
 'Cabo San Lucas',
 'Colon',
 'Ho Ha Wan Marine Park',
 'Tiburon Peninsula',
 'Moray',
 'Bocas Del Toro Province',
 'Bonin Islands',
 'Beaufonds',
 'Tongatapu',
 'Argyll',
 'Between Beira & Maputo',
 'Romblon Province',
 'Between Kwajalein Atoll & Johnston Island',
 'Wake Island',
 'Holquin Province',
 'South Atlantic Ocean',
 'Between Australia & Usa',
 'Off Vanua Levu',
 'Sharon',
 'Off South American Coast',
 'Gulf Of Suez',
 'Cook Islans',
 'Delta',
 'Gulf Of Tadjoura',
 'Ratak',
 'Northwest Italy',
 'Fife',
 'Between Hawaii And U.S.A.',
 '10S, 142E',
 'Chatham Islands, East Of New  Zealand',
 'Imperia Province',
 'Kedah',
 "L'Etang-Sal",
 'Golfo Di Genova In The Ligurian Sea',
 'Istanbul',
 'Missouri',
 'Panama Bay (Pacific Ocean)',
 'Umm Al Qaywayan Province',
 'Southern Cyprus',
 'Roncador Bank',
 'Yucatan Channel',
 '300 Miles East Of St. Thomas (Virgin Islands)',
 'Brittany',
 'Rio San Juan',
 'Marovo Lagoon',
 'Muhafazat Hadramawt',
 'South Coast, East New Britain',
 'Pinas Bay',
 "L'Etang-Sale",
 'Gujarat',
 'Tamilnadu',
 'Off Ireland',
 'Baatan',
 'Wake Island (Enenkio)',
 'Moluccas',
 'Off Coast Of Ecuador',
 'Granada',
 'Kwajalein',
 'North Palawan',
 'Phang Nga Province',
 'Alaska',
 'Magdalena Department',
 'Maluku Province',
 'South Of The Equator',
 'Zambesi River',
 'Shefa Province',
 'East Flores',
 'Wakaya Island',
 'Skagerrak Arm Of The North Sea',
 'New Brunswick',
 '5Aint-Denis',
 'Batangas Province',
 'Tafea Province',
 'Northern (Oro) Province',
 'Puntarenas Province',
 'Western Luzon Island',
 'Mindoro',
 '40 Miles South Of Naples',
 'Aulong Island',
 'Off The Western Coast Of Peninsular Malaysia',
 'KhNh HA Province',
 'Norfolk Island',
 '600 Nm West Of The Canary Islands',
 'Ascension Bay',
 '200 Nm Southeast Of Manila',
 'North Pacific Coast',
 'Salerno',
 'Bay Of Bengal',
 'Antibes',
 'Baie De Sainte-Marie',
 'Western Banks',
 'Bayelsa State',
 "3539 : 1658'",
 'Central Philippines',
 'Moorea',
 'Jakarta Harbour',
 'Nice & Marseilles',
 'Worcestershire',
 'Cape Coast',
 'Isles Del Rosario',
 'Easter Ross',
 '60 Miles North Of San Domingo In The West Indies',
 'Transvaal',
 'Malaita Province',
 'Makira-Uluwa Province',
 'St. Anne',
 'Rodrigues',
 'Illinois',
 'East New Britain',
 'West Africa',
 'Sfax',
 'Tuamotos',
 'Calvados Archipelago',
 'Savona',
 'Between Noumea & Sydney',
 'Okinawa Prefecture',
 'Ahirkapi Coast',
 'Between Perth & Colombo',
 'Between Comores & Madagascar',
 'Herzliyah',
 'Adana Province',
 'Tavenui',
 'Basrah City',
 "South Ch'Ungch'Ong Province",
 'New Ireland, Bismarck Archipelago',
 'Between Timor & Darwin, Australia',
 'Strait Of Malacca',
 'CortS',
 'East Yorkshire',
 'Bwagaoia',
 'Santa Cruz Island',
 'South Korea',
 'Liguaria',
 'Pearl Islands',
 'Santiago Island',
 'Suez',
 'Boa Vista Island',
 'Telyakovsky Bay, Khasan,  Primorsky Krai (Far East)',
 'North China',
 'Quezon',
 'East Of The Gulf Of Aqaba',
 'Rangiroa',
 'Mexico / Caribbean Sea',
 'In Transit Between Tinian And Leyte',
 'Cape Haitien',
 'Turtle Bogue',
 'Northwest Of Viti Levu',
 'Near The Fiji Islands',
 'Vancouver',
 'North Region',
 'Port Shelter',
 'Bikini Atoll',
 '400 Miles Southeast Of Sri Lanka',
 'Clarendon',
 'Argyllshire',
 'Bay Of Biscay',
 'Northwest Of Papua New Guinea',
 'Costa Blanca',
 'Alagoas',
 'Bay Of Fundy',
 'Bardestrand',
 'Panama',
 'Santa Isabel Province',
 "L' Etang Sal-Les-Bains",
 'Ganges-Brahmaputra Delta',
 'Lau Province',
 'South Pacific Ocean',
 'Apolima Strait',
 'Harare Province',
 'Woodlark Islands',
 'Masbate',
 '18S / 50E',
 'Lukovo',
 'Maine',
 'Island Of St. Thomas',
 'Phuket',
 'Amirante Islands',
 'La Saline-Les-Bains',
 'Antsiranana Province',
 'Saipan',
 'In The Gulf Stream',
 'Abau Subdistrict,Central Province',
 'Reggio Calabria Province',
 'Halifax',
 'Balearics',
 'Namonuito Atoll',
 'Bay Of Monaco',
 'Tabuk Province',
 'Lomaiviti Provine',
 'Grand Turk Island',
 'Elqui Province',
 'Walkers Cay',
 'Estuaire Province',
 'South Chungcheong Province',
 'Strait Of Messina',
 'Kowloon Peninsula',
 'Salinas Bay',
 'Island Of Kos',
 'Carabobo',
 'Biserta',
 'Gran Canaria',
 'Madang (Wo)',
 'Ryukyu',
 'Central Tuamotu',
 'Los Roques  Islands',
 'North Devon',
 'Line Islands',
 'Andalucia',
 'North Sumatra',
 'Makora-Ulawa Province',
 'Isle Of Man',
 'Catalunya',
 'Kwazulu-Natal Between Port Edward And Port St Johns',
 'Teramo',
 'Singapore Harbor',
 'Cargados Carajos Shoals (St. Brandon)',
 'Southern Japan',
 'Mozambique Channel',
 'Coquimbo',
 'Brindisi Province',
 'Lower San Juan River',
 'South Devon',
 'Mangaia Island',
 'Valpariso Province']

In [42]:
# Same for location column

list(df["Location"].value_counts().index)

df['Location'] = df['Location'].str.title() 
df['Location'] = df['Location'].str.replace("�","")
df['Location'] = df['Location'].str.lstrip().str.rstrip()

In [43]:
# Check activity column

list(df["Activity"].value_counts().index)

['Surfing',
 'Swimming',
 'Fishing',
 'Spearfishing',
 'Bathing',
 'Wading',
 'Diving',
 'Standing',
 'Snorkeling',
 'Scuba diving',
 'Body boarding',
 'Body surfing',
 'Swimming ',
 'Pearl diving',
 'Treading water',
 'Kayaking',
 'Boogie boarding',
 'Free diving',
 'Fell overboard',
 'Windsurfing',
 'Boogie Boarding',
 'Shark fishing',
 'Walking',
 'Surf-skiing',
 'Rowing',
 'Floating',
 'Surf skiing',
 'Fishing ',
 'Canoeing',
 'Surf fishing',
 'Fishing for sharks',
 'Kayak Fishing',
 'Sponge diving',
 'Freediving',
 'Diving for trochus',
 'Sitting on surfboard',
 'Sailing',
 'Sea disaster',
 'Fell into the water',
 'Surfing (sitting on his board)',
 'Skindiving',
 'Spearfishing ',
 'Floating on his back',
 'Playing',
 'Boating',
 'Free diving for abalone',
 'Paddle boarding',
 'Diving for abalone',
 'Murder',
 'Spearfishing on Scuba',
 'Kite Surfing',
 'Surf skiing ',
 'Sea Disaster',
 'Fishing for mackerel',
 'Dangling feet in the water',
 'Paddleskiing',
 'Hard hat diving',
 'Freedom swimming',
 'Boat',
 'Shipwreck',
 'Fishing on a boat',
 'Spearfishing / free diving',
 'Freedom Swimming',
 'Seine netting',
 'Fishing boat',
 'Skin diving',
 'Jumping',
 'Splashing',
 'Scuba diving (but on surface)',
 'Paddling on surfboard',
 'Body-boarding',
 'Clamming',
 'Diving for coins',
 'Scuba diving (submerged)',
 'Lifesaving drill',
 'Jumped into the water',
 'Wade Fishing',
 'Stand-Up Paddleboarding',
 'Competing in the Woodvale Atlantic Rowing Race',
 'SCUBA diving',
 'Spearing fish',
 'boat capsized',
 'Fishing for kob',
 'Shark watching',
 'Fishing for snapper',
 'Escaping from Alacatraz',
 'Body Boarding',
 'Standing in knee-deep water',
 'Scuba diving for abalone',
 'Sitting on gunwale of boat',
 'Wade fishing',
 'Crayfishing',
 'Sculling',
 'Shell diving',
 'Walking out of the water after surfing',
 'Scuba Diving',
 'Boat swamped',
 'Spearfishing (free diving)',
 'Fishing for bluefish',
 'Tagging sharks',
 'Feeding fish',
 'Kite surfing',
 'Surfing ',
 'Surfing, paddling seawards',
 '.',
 'Floating on a raft',
 'Hookah diving for abalone',
 'Jumped overboard',
 'Unknown',
 'Diving ',
 'Wreck of the schooner Pohoiki ',
 'Wade-fishing',
 'Crabbing',
 'Playing in the surf',
 'Kayaking / Fishing',
 'Free diving & spearfishing',
 'Diving for sponges',
 'Spearfishing / Scuba diving (at surface)',
 'Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days',
 'S2N Navy scout plane went down, E.H. Almond & Lieut A.G. Reading in water',
 'Spearfishing / Free diving',
 '"Flying Tiger" transport plane went down with 5 men onboard',
 'Kayak fishing',
 'Diving for beche-de-mer ',
 'Diving around anchored liner',
 'Splashing ',
 'Swimming from the New Venture ',
 'Diving from canoe',
 'Aircraft crashed into sea',
 'Teasing a shark',
 'Washing his feet',
 'Jumped overboard ',
 'Surfing, collided with shark',
 'Beach seine netting',
 'Shooting sharks ',
 'Fishing for tuna',
 'Standing / Surfing',
 'Free diving / Spearfishing',
 'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water',
 'Floating on back',
 'Boat capsized, swimming ashore',
 'Knocked overboard',
 'Cruising',
 'Fishing for cod',
 'Floating in inner tube',
 'Sitting in shallows',
 'Kayaking ',
 'Swimming / Wading',
 'Surfing (lying prone on his board)',
 'Standing ',
 'Diving for crayfish',
 'Spearfishing using Scuba',
 'Jet skiing',
 'Fishing for lobsters',
 'Swimming / escaping imprisonment ',
 'Swimming after his hat',
 'The Christie V sank on 11/6/1988, survivors were adrift on a dinghy',
 'Hookah diving for sea urchins',
 'Kite boarding',
 'Diving for beche-de-mer',
 'Air disaster',
 'Suicide',
 'Body surfing / treading water',
 'Swimming / snorkeling',
 'Playing in the water',
 'Scuba diving & spearfishing',
 'Attempting to kill a shark with explosives',
 'Diving for lobsters',
 'Standing in waist-deep water',
 'Sitting in the water',
 'Bathing ',
 'Swimming, ducking for shells in water 0.9 m deep',
 'Fishing (Seining)',
 'Shark diving',
 'Fishing for whiting',
 'Swimming alongside NOAA research vessel Discoverer',
 'Bathing in river',
 'Kitesurfing',
 'U.S. Airforce C124 enroute from Hickham Air Base to Japan went down. The 3 survivors fashioned raft from mailbags  & were rescued 3 days after the crash.',
 'Shark tagging',
 'HMAS Parramatta torpedoed & sunk by the U-559',
 'Thrown overboard',
 'Collecting shells',
 'Finning the shark that bit him',
 'Hoisting shark aboard fishing boat',
 'Ocean racing',
 'fishing boat exploded & sank',
 'Diving into water',
 'Diving off jetty',
 'Dived for a coin',
 'Kite Boarding',
 'Spearfishing / Scuba diving',
 'Diving?',
 'Transatlantic Rowing',
 'Fishing for squid',
 'Free diving, Spearfishing',
 'Air Disaster',
 'Fishing from surf ski',
 'Washing',
 'Fishing for prawns',
 'Swimming or surfing',
 'Netting shrimp',
 'Free-diving',
 'Diving for trochus shell',
 'Free diving / spearfishing',
 'Swimming ashore from capsized boat',
 'Swimming near jetty',
 'Boat with 5 men capsized while returning to the Amerique',
 'Paddling',
 'Spearfishing Competition',
 'Rowing ',
 'Launching rowboat through the surf',
 'Kiteboarding',
 'Fishing for white shark',
 'Fishing / washing bait off hands',
 'Attempting to ride a shark',
 'Steinhart Aquarium',
 'Defecating in water beneath the docks',
 'bathing ',
 'Harassing a shark',
 'Cargo ship El Gamil entroute Suez to Yemen (Aden) when her cargo shifted and she sank. 19 Egyption sailors jumped into the water and swam for several hours before being bitten by sharks',
 'Fell from yardarm of British ship Rover',
 'Observing a shark feeding on a carcass of a humpback whale',
 'Diving (shell maintenance)',
 'Boat stopped to repair electric pump',
 'Swimming or Snorkeling',
 'Standing in waist-deep water, helping his father tend a gill net containing dead fish',
 "Scientific research (Dr. Sonny Gruber's student)",
 'Floating face-down in knee-deep water',
 'Attempting to retreive a dinghy',
 "Swimming at surface through school of feeding 2.5' to 5� sharks",
 'Diving for pearls',
 'The Dwarka foundered',
 'Watching the shark feeding on a dead pinniped',
 'Swimming 10 m from shore',
 'Exercising his dog in the shallows',
 'The World Liberty and the tanker Mosli collided. The  Halcyon Breeze sent a lifeboat to the rescue, but it was smashed, throwing 6 men in the  water.',
 '3-masted steel barque Glenbank foundered during a cyclone',
 'Unknown, but it was said to be the "First known attack in Sydney Harbour"',
 'M.V. Tropical sank. Sole survivor rode oil drums for 8 days without food or water.',
 'Towing rubber dinghy',
 'Lying in 2 feet of water',
 'Murdered',
 'The troopship Britannia was sunk by the German raider Thor',
 'Swimming in the channel',
 'Wading near a fishing net',
 'Photographing fish',
 'Surf fishing in waist-deep water',
 'Fell overboard, prop slashed arm',
 'Touching the mouth of a supposedly dead shark',
 'Dutch merchant ship Zaandam torpedoed  by the U-174 amidships, sank & dozens of survivors took to rafts & boats. One man, Izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down',
 'Loss of the schooner Nomad',
 'Playing in the surf with his 2 dogs',
 'Free diving / modeling',
 "Fishing, caught a 15' shark & took it onboard",
 'Colombian  (Avianca) DC-4 airliner plunged into the sea 5 minutes after takeoff',
 'Fleeing across a river',
 'Swimming with pod of dolphins',
 'Abalone diving using Hookah (near calving whales)',
 'Surfing, but treading water',
 '"Crossing the river"',
 'Swimming along a row of nets',
 'Sitting on side of dinghy mending a net',
 'Swimming with other crew near wharf',
 'Reached out to disentangle rope & fell overboard',
 'Freediving, inspecting Kaunakakai wharf construction after blasting & dredging ',
 ' ',
 'Skin diving for trepang but at surface next to the boat',
 'Spearfishing, had fish on his spear',
 'Fishing, holding fish in right hand',
 'Paddling a surfboat',
 'Inspecting teeth of supposedly dead (hooked & shot) shark',
 'Floating with life buoy after pilot launch capsized',
 'Swimming with goggles',
 'Fishing in ankle-deep water',
 'Swimming near pier',
 'Fishing in knee-deep water',
 'Removing shark from a trap',
 'A junk foundered',
 'Boat capsized, swimming to shore',
 'Attempted to return injured shark to the sea',
 'Sitting',
 'seaplane Columbus ditched in the sea',
 'Swimming off yacht',
 'Swimming, after falling overboard',
 'Boat capsized?',
 'Swimming, using bundles of sticks as raft',
 'Conducting a promotional film project for the Gemini space program (a practice astronaut recovery)',
 'Oystering',
 'Returning to shore, collided with shark',
 'Bather',
 'Floating near boat & observing bioluminesce',
 'Shrimping',
 'Commercial Salvage Diving',
 'Thrashing the water / imitating the shark victim from "Jaws"',
 'The 500-ton coastal trader Polurrian foundered ',
 'The British steamer Caribbee foundered',
 'Vessel caught fire & capsized, survivors in the water',
 'Wreck of the 150-ton brig Maria',
 'Wading to dinghy, carrying his son',
 'boat from ship Josephine capsized in squall',
 'In rubber dinghy with Captain Eddie Rickenbacker for 21 days. ',
 'Free diving for trochus',
 'Swimming or snorkeling',
 'Swimming from shore to anchored sailboat',
 'Hooking into a whale',
 'Explosion & sinking of the USS Juneau after being torpedoed by the submarine  I-85',
 '17 Maldivians adrift in open boat for 31 days',
 'Fishing in waist-deep water',
 'Swimming with fish attached to  belt',
 'Swimming alongside the schooner Catherine Wilcox',
 'Walking in surf',
 'Catching a turtle',
 'Gaffing netted shark',
 'Swimming alongside yacht Mexico Fiesta',
 'Attempting to net shark in shark channel',
 'Swimming to avoid capture',
 'Spent 8 days in dinghy',
 'Playing with a frisbee in the shallows',
 'Boarding a ship',
 'Collecting ornamental fish',
 'Chasing shark out of bathing area while riding on a surf-ski',
 'Stamding',
 'Paddle-surfing',
 'Sitting in a boat',
 'Air Disaster - Piper aircraft crashed into the sea, killing all on board',
 'Unknown, their unoccupied yawlboat was recovered',
 'Swimming to shore from capsized sailboat',
 'Removing hook from shark',
 'Wooden fishing boat',
 'Fishing boat swamped in a storm',
 'Swimming after falling overboard',
 'She was on a ship that was torpedoes & was in the water awaiting rescue',
 'Working on the bridge when he fell into the river',
 'Dived from inner-tube',
 'Capsized fishing boat',
 'Swimming to shore from the Medic',
 'Diving off wharf',
 'Swimming, naked',
 'male',
 'Conducting research',
 'Spearfishing, but swimming at surface',
 'Standing, collecting bananas',
 'Lifesaving exhibition',
 'Dismantling cable buoys of the cable ship All America',
 'Scuba diving, reportedly also spearfishing',
 'Fishing for rock lobster',
 'Swimming in waist-deep water ',
 'A 75-ton  Japanese fishing ship was sunk by  Chinese Nationalist gunboat, shipwrecked men were clinging to debris',
 'Swimming in canal',
 'Snorkeling on surface',
 'Swimming (using a float)',
 'Walking in shallows',
 'Surfing (or sailboarding)',
 'Skindiving,',
 'Sinking of the ferryboat      Don Juan',
 'yachtsman in a zodiac',
 'Swimming behind sailboat',
 'Feeding mullet to sharks',
 'Swimming, attacked at  surf carnival',
 'Arsinoe, a French tanker',
 "Attempting to lasso shark's tail",
 'Fishing for snoek & yellowtail',
 'Commercial fishing vessel, Ev-nn, struck object & sank. Ken Crosby and  Jame & Ann Dumas adrift on makeshift raft.',
 'Scuba diving (ascending using scooter)',
 'Free diving for molluscs',
 'Surf fishing / wading',
 'Wreck of the steamship Sultan of Bombay',
 'Aircraft ditched in the sea, swimming ashore',
 'Row boat (from the gunboat Elcano) was sinking, put finger in hole',
 'Fishing / standing in waist deep water',
 'Attempting to drive shark away from sailing regatta',
 'Fell overboard, hanging onto lifebuoy',
 'Fishing from prawn trawler',
 'Spearfishing, but swimming on surface',
 'Swimming & splashing',
 "Filming 5' blue shark",
 'Fell off aircraft carrier',
 'Fishing from boat, Kaimamla',
 'Anti-Aircraft cruiser USS Atlanta (CL,-05) travelling in convoy after the Battle of Midway, encountered a Japanese flotilla  (Battle of Guadalcanal) &, heavily damaged by gunfire, she was lost off Lunga Point. Victim was swimming when bitten.',
 'Small boat with 2 men onboard hit a submerged coral formation. Men began swimming to shore',
 'Crossing the bay at the ford',
 '3,909-ton Panamanian freighter Chieh Lee sank in a typhoon',
 'Diving for sinkers',
 'Dived into a school of baitfish',
 'Closed circuit diving (submerged). Diving to recover jettisoned packets of opium for police',
 'Anti-sabotage night dive exercise alongside destroyer (Scuba diving)',
 'Surfing, fell off surfboard',
 'Went to aid of child being menaced by the shark',
 'Fishing, hauling in net, shark in net',
 'Air/Sea Disaster Pan-American Airlines Stratocruiser with 44 people onboard crashed into the sea',
 'Body surfing or body boarding',
 'Free diving , but surfacing',
 'Sailboarding, fell into water 100 yards outside the breakwater',
 'Swimming after boat became disabled',
 "Boat capsized between O'ahu & Molokai",
 'Torpedoed & burning British  light cruiser with a crew of 450 men',
 'Fishingat',
 'Dragging stranded shark ashore',
 'The 6015-ton British ship Empire Avocet was torpedoed by the German submarine U-125. ',
 'Steamer Una wrecked with 75 laborers onboard. Survivors took to rafts & lifeboats.',
 'Free diving & spearfishing (ascending)',
 'The shrimper Loless Maurine capsized in heavy seas & the men were swimming ashore  ',
 'Swimming to shore from capsized kayak',
 'Netting pilchards',
 'Free diving for shell',
 'Swimming with speared fish',
 'Collecting fish in military trap when bitten by captured shark that had been shot by soldiers with Garten',
 'Free diving for abalone (ascending)',
 'boat from the Austrian ship Elizabeth',
 'Plane crashed in water, men in life raft',
 'Swimming out to porpoises ',
 'The steamships Thingvalla and Geiser collided',
 'Filming & feeding captive sharks',
 'Fishing, Struck by another shark when removing shark from line',
 'Trailing hand in the water',
 'Canoe capsized by shark',
 'USS Hoel DD 533 sunk on 10/24/1944 in the Battle off Samar. 2 crewmen were swimmng alongside a floater net &',
 'Diving, retrieving film package from Titan 3C rocket',
 'Surfing or body surfing',
 'Fishing, standing in water washing fish',
 'Light aircraft ditched at sea',
 'Fishing, holding fish',
 'Trying to catch a wounded bird',
 'small boat',
 'Lying atop surfboard',
 'Fishing, one of three fishermen swept into the sea by a large wave ',
 'Free diving for abalone from Zodiac (submerged)',
 'His balloon crashed in the harbor',
 'U-177 torpedoed & sank the troopship Nova Scotia',
 'Swimming / floating on his back',
 'Fishing from shore, washed into the sea',
 'Accidentally thrown overboard & treading water while awaiting rescue',
 'Helmet diving, collecting trochus shell',
 'Net fishing, fell into the water',
 'Fishing trawler Flavio Gioia ',
 'Lifeboat capsized',
 'Boogie boarding or Surfing',
 'Swimming underneath house on pilings',
 'Wading or swimming',
 'Swimming, when caught in heavy seas',
 'Surfing, but lying prone on his board',
 'Inebriated, woke from sleep and fell off deck into the water ',
 'Shark fishing, knocked overboard',
 'yachting accident',
 'Fishing, two large sharks passed. He speared one and it bit him',
 'Italian liner Principessa Mafalda sank',
 'Spearfishing, shot shark, hauled it onto boat',
 'Bathing alongside the American ship Thomas W. Sears',
 'Sea Disaster, sinking of the  SS Vestris',
 'Japanese POW ship Arisan Maru with 1800 American prisoners of war on board bound for slave labor camps was torpedoed by an American submarine',
 'Playing / standing',
 'Swept out to sea by the tsunami, she clung  to a log for 24 hours',
 'Spearfishing / scuba diving',
 'Finning the shark',
 '1446-ton Norwegian barque Errol, bound from Peru to Newcastle with 22 on board wrecked. Survivors shelterd on the wreck of the Annasona. Subsequently the Master, his wife & 4 children perished along with several crew. Survivors (5) were rescued 7/12/1909',
 'Standing alongside surfboard',
 'Sea Disaster, sinking of the motorship Wingate',
 'Spearfishing, but walking carrying fish on end of speargun',
 'Paddle Boarding',
 'Splashing in water ',
 '"Boat accident"',
 'British patrol boat 1250-ton HMS  Valerian foundered in a hurricane',
 'Surf fishing, wading ',
 'Free diving / photography, kneeling on sand',
 'Filming a documentary',
 'Air disaster: crash of Air France Super Constellation ',
 'Scuba diving & U/W photography',
 'Fishing for snappers & cleaning mullet. Put mullet over side of boat to wash it',
 'Attempting to chase shark out to sea',
 'Leaving the water',
 'Shark Fishing',
 'Swimming ashore from fishing boat swamped and sunk by a squall',
 'Commercial spearfishing',
 'Sailing on catamaran & fell into the water',
 'Fishing, on charter boat Silver Dollar',
 'Picking up shark by the tail',
 'Bathing / standing',
 'Bottom fishing for lingcod & had hooked a fish',
 'Testing anti-shark cage',
 'Standing, holding shark pup',
 'Knocked into the water',
 'Scuba Diving for scallops',
 'Resting on body board',
 'Survived US Naval aircraft crash, climbing onboard rescue vessel when he fell back into sea ',
 'Clinging to shipwrecked junk',
 'Helping friend land hooked shark',
 'Boat of a Hawaiian brig was stove in by  whale',
 'Steamer Durao struck rock & filled, boats capsized, passengers & crew tried to swim to shore',
 'Snorkeling (filming the sardine run)',
 'Fell overboard from sponge vessel',
 'Wading to shore from his boat',
 "A man's head found in a shark caught by British steamer Syria",
 'Boat capsized',
 'Paddle-boarding',
 'Floating in tube',
 'S2F-1 airplane crashed immediately after carrier take-off',
 'Lying prone on surfboard',
 'Swimming or wading out  to warn bathers that a shark had been seen',
 'Fishing for squid aboard the trawler Shikishima-Maru when the shark leapt into the boat',
 'Bathing alongside US Naval ship',
 'Trailing the field in a surf race',
 '"Swimming vigorously"',
 'Shipwrecked; adrift on raft for 2 days & 2 nights',
 'Taking wife to beach & about 1 m from the shore',
 'SCUBA Diving',
 'Fell overboard?',
 'Swimming, after sailboat capsized',
 'Attempting to rescue crew after whale upset their boat',
 'Diving alongsidethe steamship Ranelagh ',
 'Fishing, speared shark upset canoe & man fell in water',
 'Floating ',
 'Scuba diving, attempting to catch a captive shark',
 'Sinking of the ferryboat Dumaguete ',
 'Walking in chest-deep water',
 'Taking catch from a fish weir in which the shark was snared',
 'Floating on his back in an inner tube',
 'Wading / fishing & carrying a bag of fish',
 'R5D aircraft went down with 29 on board',
 'Helping angler land a shark',
 'Among 31 survivors of crew from the sampan Fukulya Maru (which reached Thursday Island in rowing boat) was a man whose arm had been bitten off by shark. The sampan wrecked west of McArthur island ',
 'Diving (Helmet) for sponges',
 'Spear fishing',
 'Wreck of the 1308-ton Norwegian ship Auckland',
 'Lost his footing & fell overboard',
 'Adrift in a life jacket',
 'Hunting turtle',
 'Diving for pearl shell',
 'Riding a horse',
 'Netting menhaden, sharks caught in net',
 'Crossing the river mouth',
 "Spearfishing, holding 5' speared fish",
 'Fishing with hand line tied to wrist & was pulled into the water',
 'Kayaking (returning from spearfishing)',
 "On board 51' fishing vessel One Ki",
 'Hauling in net with shark in it',
 'The 6711-ton American freighter & troop transport Cape San Juan was torpedoed by the Japanese submarine I-21',
 'Chumming for sharks',
 'Fishing for bluefish, shark leapt into dory',

In [44]:
# Rename sex column

df = df.rename(columns={"Sex ": "Sex"})

In [45]:
# make Sex column to only M and F
df.loc[df["Sex"] == "M ", ["Sex"]] = "M"
df.loc[df["Sex"] == ".", ["Sex"]] = ""
df.loc[df["Sex"] == "lli", ["Sex"]] = ""
df.loc[df["Sex"] == "N", ["Sex"]] = ""
df.loc[df["Sex"] == "", ["Sex"]] = np.nan

In [46]:
# Make sex column binary

df["Sex"] = df["Sex"].str.replace("M","1").str.replace("F","0")

df = df.rename(columns={"Sex": "Sex_Male"})

In [47]:
# Check injury column

list(df["Injury"].value_counts().index)

['FATAL',
 'Survived',
 'Foot bitten',
 'No injury',
 'Leg bitten',
 'Left foot bitten',
 'No details',
 'Right foot bitten',
 'Hand bitten',
 'Thigh bitten',
 'No injury, board bitten',
 'FATAL, body not recovered',
 'Minor injury',
 'Foot lacerated',
 'Calf bitten',
 'Right leg bitten',
 'Arm bitten',
 'Lacerations to foot',
 'Ankle bitten',
 'Right calf bitten',
 'Lacerations to right foot',
 'Lacerations to left foot',
 'No injury to occupants',
 'Heel bitten',
 'Left leg bitten',
 'No injury, surfboard bitten',
 'Left arm bitten',
 'Foot severed',
 'Right thigh bitten',
 'Leg lacerated',
 'Leg severed',
 'Minor injuries',
 'Left calf bitten',
 'FATAL, leg severed ',
 'Leg injured',
 'Thigh lacerated',
 'Legs bitten',
 'Lacerations to right leg',
 'Lacerations to leg',
 'Probable drowning & scavenging',
 'Left foot lacerated',
 'Lacerations to lower leg',
 'Lacerations to right hand',
 'Laceration to left foot',
 'Left hand bitten',
 'Right foot lacerated',
 'Puncture wounds to foot',
 'Knee bitten',
 'Lacerations to hand',
 'No injury, kayak bitten',
 'Lacerations to left calf',
 'Arm severed',
 'Arm lacerated',
 'Hand lacerated',
 'Laceration to leg',
 'Lacerations to left leg',
 'No injury, ski bitten',
 'Forearm bitten',
 'Leg bitten, surgically amputated',
 'No injury, shark bit surfboard',
 'FATAL, legs bitten ',
 'Left arm lacerated',
 'Lacerations to fingers',
 'Lacerations to arm',
 'Lacerations to thigh',
 'FATAL ',
 'Torso bitten',
 'Left thigh lacerated',
 'Lacerations to left forearm',
 'FATAL, thigh bitten ',
 'Lacerations',
 'Right hand lacerated',
 'Swim fin bitten',
 'Right calf lacerated',
 'Hand severed',
 'Laceration to right foot',
 'Shoulder bitten',
 'FATAL x 2',
 'Puncture wounds to right foot',
 'Foot & ankle lacerated',
 'Right foot & ankle lacerated',
 'Leg severely bitten, surgically amputated',
 'Calf lacerated',
 'Lacerations to left hand',
 'Elbow bitten',
 'No injury, board damaged',
 'Finger bitten by hooked shark PROVOKED INCIDENT',
 'Hip bitten',
 'Right hand bitten',
 'Right leg lacerated',
 'Shark involvement prior to death unconfirmed',
 'Minor injury to leg',
 'Laceration to left thigh',
 'No injury, swim fin bitten',
 'Laceration to thigh',
 'Laceration to left hand',
 'Lower leg bitten',
 'Buttocks bitten',
 'PROVOKED INCIDENT',
 'Right arm bitten',
 'Recovered',
 'Right hand severed',
 'Hand injured',
 'Right thigh lacerated',
 'Thigh & calf bitten',
 'Probable drowning / scavenging',
 'Left thigh bitten',
 'Left calf lacerated',
 'Lower right leg lacerated',
 'Laceration to calf',
 'FATAL, body was not recovered',
 'Left ankle bitten',
 'Probable drowning with post-mortem bites',
 'Shark involvement prior to death was not confirmed',
 'Laceration to right lower leg',
 'Torso lacerated',
 'Lacerations to calf',
 'Minor injury to left foot',
 'Death may have been due to drowning',
 'No injury, board bumped by shark',
 'No injury to occupants, shark bit boat',
 'Laceration to right leg',
 'Lacerations to lower left leg',
 'Right hand bitten by hooked shark PROVOKED INCIDENT',
 'Lacerations to right calf',
 'Buttock bitten',
 'No Injury',
 'FATAL, torso bitten ',
 'Laceration to foot',
 'No Injury, board bitten',
 'Left leg lacerated',
 'Puncture wounds to right thigh',
 'Left forearm bitten',
 'Lower leg lacerated',
 'Lacerations to head',
 'No injury, shark bit board',
 'Foot injured',
 'Human remains found in shark',
 'Leg bitten ',
 'Minor lacerations to foot',
 'Big toe bitten',
 'Presumed FATAL, body not recovered',
 'FATAL, but shark involvement prior to death unconfirmed',
 'Shin lacerated',
 'Minor injuries to foot',
 'Ankle & foot lacerated',
 'No injury, knocked off board',
 'FATAL, right thigh bitten ',
 'FATAL, left leg severed',
 'Minor injuries to hand',
 'Abdomen bitten',
 'Minor injury to calf ',
 'Shark involvement not confirmed',
 'Ankle lacerated',
 'Thigh bitten, FATAL',
 'Non-fatal',
 'Presumed FATAL',
 'No injury to occupant',
 'Ankle & foot bitten',
 'Arm bitten by hooked shark PROVOKED INCIDENT',
 'Right ankle & foot bitten',
 'Puncture wounds on right foot',
 'Severe laceration to foot',
 'Leg bitten by hooked shark PROVOKED INCIDENT',
 'No injury, shark bit kayak',
 'Left forearm bitten PROVOKED INCIDENT',
 'Laceration to left leg',
 'Knee & calf lacerated',
 'Lower left leg bitten, surgically amputated',
 'Arm bitten by captive shark PROVOKED INCIDENT',
 'Lacerations to legs',
 'Lower left leg & foot bitten',
 'Missing, believed taken by a shark',
 'Left ankle & foot bitten',
 'No injury, rammed by shark',
 'Right forearm lacerated',
 'No Injury to occupants',
 'Abrasions',
 'Abrasion',
 'Heel lacerated',
 'Minor injury to ankle',
 'Shark bites were post-mortem',
 'No injury to occupants, shark bit propeller',
 'Left leg severely bitten',
 'Lacerations to right forearm',
 'Right ankle bitten',
 'Lacerations to knee',
 'FATAL, "bitten in two"',
 'FATAL, leg bitten ',
 'Leg bitten by netted shark PROVOKED INCIDENT',
 'FATAL, multiple bites ',
 'Knee lacerated',
 'Chest lacerated',
 'FATAL, but shark involvement prior to death was not determined',
 'Minor injury to foot',
 'Leg severed at knee',
 'Left foot severed',
 '2 toes bitten off ',
 'No injury to occupants, boat damaged',
 'Right knee lacerated',
 'Foot bitten by landed shark PROVOKED INCIDENT',
 'Upper left arm bitten',
 'Minor laceration to hand',
 'No injury to occupants, shark rammed boat',
 'FATAL?',
 'Small lacerations on right lower leg',
 'Hand injured PROVOKED INCIDENT',
 'Lacerations to thigh & buttocks',
 '2-inch laceration to upper left arm',
 'Arm bitten, surgically amputated',
 'No injury, paddleboard bitten',
 'Lacerations to buttocks & thigh',
 'Thought to have been taken by a shark',
 'No injury. Hull bitten, tooth fragment recovered',
 'Shin bitten',
 'Lacerations to forearm',
 'Right leg severed',
 'Right leg severely bitten',
 'Thigh gashed',
 'Lacerations to left lower leg',
 'Multiple lacerations',
 'No inury to occupants, shark struck boat',
 'Laceration to toe',
 'Toe bitten',
 'Lacerations to lower leg & ankle',
 'Buttock & leg bitten',
 'No injury, shark made a threat display',
 'No injury, bumped off board by the shark',
 'FATAL, some were taken by sharks',
 'Laceration to right heel',
 'Right arm severely bitten',
 'Left shoulder bitten',
 'Thought to have been taken by a shark. Body was not recovered',
 'Puncture wounds to left foot',
 'Lower legs bitten',
 'Hands severed',
 'FATAL, leg severed',
 'Puncture wounds to right calf',
 'FATAL, leg severely bitten',
 'Recorded as PROVOKED INCIDENT',
 'FATAL PROVOKED INCIDENT',
 'Arm severely lacerated',
 'Severe injury to arm',
 'Lower leg & foot bitten',
 'Missing, thought to have been taken by a shark',
 'Lower right leg bitten',
 'Severe lacerations to left foot',
 'Left forearm lacerated',
 'Posterior thigh bitten',
 'Foot nipped',
 'FATAL, thigh bitten',
 'Hand bitten ',
 'Laceration to arm',
 'Leg severely bitten',
 'Severe lacerations to arm',
 'Right ankle & foot lacerated',
 'Hooked shark bit boat PROVOKED INCIDENT',
 'Buttocks & hip bitten',
 'Bitten by harpooned shark PROVOKED INCIDENT',
 'Arm injured',
 'FATAL,  beaten & thrown overboard by smugglers, they  were killed by sharks',
 'No injury, surfboard leash severed',
 'Finger severed',
 'Left hand severed',
 'Laceration to leg by hooked shark  PROVOKED INCIDENT',
 'Death resulted fom drowning; shark bites were post-mortem',
 'Left calf injured',
 'FATAL, legs severed  ',
 'No injury, shark bumped surfboard',
 'Lacerations to right arm',
 'Shark leapt onto surfboard; surfer uninjured ',
 'Laceration to forearm',
 'Toe severed',
 'Left knee lacerated',
 'Thigh & foot bitten',
 'Left foot & ankle lacerated',
 'Left arm severed',
 'Fatal or drowning or scavenging',
 'Calf & foot lacerated',
 'No injury to occupant, shark bit boat',
 'Probable drowning ',
 'Leg severed below knee',
 'Lacerations to  foot',
 'Foot & ankle bitten',
 'FATAL  ',
 'Lacerations to left ankle',
 'Laceration to back',
 'Shark involvement prior to death not confirmed',
 'Leg abraded',
 'Head bitten',
 'Right leg severed, left leg lacerated',
 'Leg severed, but survived',
 'Lacerations to hip and leg',
 'Leg & foot bitten',
 'FATAL, leg severed  ',
 'No injury to occupant, shark/s holded  kayak',
 'Left thigh severely bitten',
 'Left foot bitten ',
 "Shark's tail broke his leg. PROVOKED INCIDENT",
 'FATAL, PROVOKED INCIDENT',
 'Punctures on left thigh',
 'Arm bitten PROVOKED INCIDENT',
 'Left elbow bitten',
 'Minor injury to thigh',
 'Back bitten',
 'Shark bites post mortem',
 'No injury, no attack',
 'Arm bitten PROVOKED INCIDENT ',
 'FATAL, leg bitten',
 'No injury, board bumped',
 'Thigh severely lacerated',
 'Wrist bitten',
 'No injury, ski bumped',
 'Laceration to left ankle',
 'Forearms lacerated',
 'Laceration to ankle',
 'Lacerations to left arm',
 'Laceration to right hand',
 'Probable drowning',
 'Right forearm bitten',
 'FATAL, but shark involvement uncomfirmed. Death may have been due to drowning.',
 'Left foot & ankle bitten',
 'No injury, kayak damaged',
 'Fatal, but death may have been due to drowning',
 'Laceration to right ankle',
 'No injury, shark damaged surfboard',
 'Cuts on right foot',
 'Right foot & ankle bitten',
 'Right thigh punctured',
 'FATAL, hand severed, both legs & arms bitten & nearly severed ',
 'Upper right thigh bitten',
 'Lacerations to right thigh',
 'Leg & surfboard bitten',
 'No injury ',
 'Disappeared, but shark involvement unconfirmed',
 'Right ankle lacerated',
 'Arm severely lacerated, surgically amputated',
 'bite to lower leg',
 'Lacerations to arm & leg',
 'FATAL, right buttock & thigh bitten ',
 'Minor lacerations to right foot',
 'Right foot severed',
 'Minor injury to left lower leg & heel',
 'Left foot lacerated ',
 'Top of left foot bitten',
 'Ankle injured',
 'Laceration to right arm',
 'Lacerations to face and neck',
 'Laceration to heel',
 'Shark bumped boat, no injury to occupants',
 'FATAL, multiple injuries to both legs  ',
 'Calf nipped in each case',
 'Minor injury to torso',
 'Right thigh bitten ',
 'Drowned, body scavenged by shark',
 'Lacerations to right foot and ankle',
 'No injury, surfboard dented',
 'No injury, shark rammed surfboard',
 'Left forearm bitten ',
 'FATAL, but shark involvement prior to death was not confirmed',
 'Lacerations to right thigh and knee',
 'Lacerations to right arm & thigh',
 'Right leg severely lacerated',
 'Lacerations to buttocks',
 'No injury to occupant, shark rammed boat',
 'No injury, knocked off surfboard',
 'Lacerations to calf by hooked shark PROVOKED INCIDENT',
 'Left foot & leg bitten',
 'Toes lacerated',
 'Forearm bitten by hooked shark PROVOKED INCIDENT',
 'Minor bite to ankle',
 'Leg & arm bitten',
 'Shark bites may have been post mortem',
 'Possible drowning victim, remains retrieved from shark caught by fishermen on 28-Apr-1976',
 "No injury to occupant, hooked shark bit boat's rudder PROVOKED INCIDENT",
 'Forearm, abdomen & upper leg lacerated',
 'Recovered at Thursday Island Hospital',
 'Left inner thigh',
 'Left thigh bitten, chest lacerated  & defense wounds on foot, fingers and hands',
 'Lower porton of body recovered 3 days later. Note: rare sighting of shark made at same beach on 11-5-1989 ',
 'FATAL, arm severed, leg bitten',
 'FATAL, left thigh, buttocks, back of spine, abdomen & chest bitten  ',
 'FATAL, thigh lacerated, femur exposed ',
 'FATAL, abdomen severely bitten. Airplane summoned from Corregidor & injured man was lashed to wing, but he died  ',
 'Hands bitten',
 'FATAL      Torso bitten',
 'Knee bitten by boated shark PROVOKED INCIDENT',
 'Right leg injured by hook and hooked shark PROVOKED INCIDENT',
 'Abrasions to left leg',
 'FATAL & some of the survivors were bitten by sharks  ',
 'Leg bitten, FATAL',
 'Minor injury to head',
 'Lacerations to thighs',
 'Groin bitten',
 'Multiple injuries, left leg surgically amputated at knee',
 'Navy personnel recovered 19 shark-scavenged bodies',
 "White shark, 3.7 m [12']  made threat display. No injury, no attack",
 'Minor injury; puncture wounds to calf',
 'Lacerations and puncture wounds to leg and foot',
 'FATAL, leg bitten from thigh to ankle',
 'No injury, shark pushed canoe from jetty to a point 100 m away',
 'Minor puncture wounds to foot',
 'Abdomen bitten & leg severed  FATAL',
 'FATAL, hip & thigh bitten with  tissue removed, including bone ',
 'Right sole & toes lacerated',
 "Possible drowning & scavenging. Remains were recovered from a 15' shark's gut",
 'Left leg bitten, surgically amputated below the knee',
 'No injury to occupants, hydrofoil of outboard motor bitten ',
 'Disappeared, body recovered with large bite on thigh',
 'Righ thigh severely bitten',
 'FATAL, gave sudden shriek & disappeared, body found in shark caught off Kahuka',
 'Right foot & heel lacerated',
 'Bodies of 5 of the 6 men on board were bitten by by sharks. Sharks may have contributed to the death of some of them.',
 'Cause of death was drowning & preceded shark involvement',
 'Left leg & foot bitten  by shark brought onboard. PROVOKED INCIDENT',
 'FATAL, abdomen & thigh bitten',
 'Thigh  severely bitten',
 'Face & thorax bitten',
 'Lassoed shark bit his hand PROVOKED INCIDENT',
 'Right arm severed, right leg bitten, not known if he survived',
 'Right shoulder blade  & back lacerated',
 'Shark and boat collided. No injury to occupants',
 'No injury, swim fin damaged',
 'Lower left leg amputated',
 'Minor cut on finger',
 "Legs nipped & he bit shark's snout",
 "Lombard's thigh was lacerated by shark that leapt into boat ",
 'Jumped off cliff',
 'Right thigh & ankle injured',
 'Injuries to chest',
 'Tip of finger amputated PROVOKED INCIDENT',
 'Abrasion to forearm',
 'Lacerations knee to ankle',
 'Puncture wounds & 3-inch laceration to right calf',
 'FATAL, left arm severed above elbow, lacerations on chest, right thumb severed, left thigh lacerated to bone, abrasions  ',
 'Tissue of right thigh removed to the bone, both thumbs & some fingers severed ',
 'Calf bitten & both hands injured',
 'Abrasions and lacerations to lower right leg',
 'Shark rammed boat PROVOKED INCIDENT',
 'Lacerations to right hand PROVOKED INCIDENT',
 'Hooked shark bit his leg, knee to ankle PROVOKED INCIDENT',
 'Arm severely injured, surgically amputated',
 'FATAL, arm bitten ',
 'Foot severely injured',
 'Left forearm bitten, surgically amputated',
 "Forearm  & hand bitten; tooth fragments of the shark were recovered from the surfer's hand",
 "No injury, surfboard 'attacked'",
 'FATAL, Drowned or crushed when harpooned shark smashed their boat PROVOKED INCIDENT',
 'No injury, tank scratched by shark',
 'Leg bitten, but survived',
 'Left knee, calf & heel bitten by shark trapped in the net PROVOKED INCIDENT',
 'Laceration & puncture wounds to foot',
 'No injury, no attack; sharks ate their food tied to a line over the side of the raft',
 'Lacerations to little finger of left hand',
 'Foot & swimfin bitten',
 'Torso bruised & abraded ',
 'Minor injury to arm. Possibly caused by smalll nurse shark',
 'FATAL, groin bitten ',
 'Lacerations to thigh & torso',
 'No injury to occupants, boat scratched by shark',
 'Possible drowning / scavenging',
 'FATAL, calf bitten twice',
 ' "Struck across loins" but no injury. According to witnesses, incident involved a bottlenose dolphin.',
 'Found at 21h30 by searchlight. Had been constantly harassed by sharks & had numerous lacerations',
 '4 punctures in left foot',
 'Of the 1346 on board, 392 perished including 90 women & 44 crew. 1 person known to have been fatally injured by a shark.',
 'Lacerations to hand, knee & thigh ',
 'FATAL, leg & buttocks removed ',
 "No injury, shark became tangled in hose & towed him 100'",
 'Calf / knee injured?',
 'Injuries to arm and shoulder',
 'Lacerations to right torso & ankle',
 'Finger or toe severed',
 'Lacerations to lower left leg, puncture wounds to sole of left foot',
 'Hip bumped by shark, no Injury',
 'Abrasions to shins',
 'Small puncture wounds to the heel of left foot',
 'PROVOKED INCIDENT?  ',
 'No attack,  no injury',
 '2-inch cut on dorsum of left foot',
 'Leg bitten by shark taken aboard Japanese trawler PROVOKED INCIDENT',
 'FATAL, left arm & left buttock severed ',
 'Abrasions to arm',
 'No injury, no attack, shark made threat displays',
 'No injury to occupant, canoe struck several times by shark ',
 'Survived. questionable incident',
 'One man was lost, but he may have drowned',
 'Left heel lacerated',
 'Minor laceration to leg',
 'Lacerations to left ankle and foot',
 'Minor laceration on left leg',
 'Ankle lacerated, lower left leg severely abraded ',
 'Minor lacerations on right ankle & foot',
 'Hooked shark gashed right leg      PROVOKED INCIDENT',
 'Thigh injured',
 'Severe bite to right leg FATAL',
 'Minor bite on foot & swimfin',
 '"Light scratch on hand/wrist area"',
 'Shoes & human remains found in a shark',
 'Coroner determined the man was killed by a boat propeller, not a tiger shark',
 'Leg severed at mid-thigh',
 'No injury, knocked off ski',
 'Hand nipped PROVOKED INCIDENT',
 'Head bitten by captive shark PROVOKED INCIDENT',
 '8 shark-bitten bodies washed ashore',
 'Right shoulder, arm & hand bitten',
 'Quadriceps lacerated, femur exposed',
 'Minor injury to arm and hand',
 'Shark bumped dinghy twice',
 'Puncture wounds to left foot & calf',
 "4 finger severed by 'dead' shark. PROVOKED ACCIDENT",
 'FATAL, arm severed, thigh severely bitten  ',
 'Lacerations to thigh by netted shark PROVOKED INCIDENT',
 'FATAL, leg severed, other leg lacerated ',
 'Left forearm grazed & puncture marks in wetsuit',
 'Both hands & heel of left foot lacerated, right foot severed',
 'PROVOKED INCIDENT Hooked shark pulled onboard bit his arm  ',
 'FATAL, right thigh severely bitten, left arm lacerated ',
 'No injury, shark bit rear of paddleboard',
 'remains of one of the crew found in shark',
 'No injury, board bumped & fin damaged',
 'Left arm amputated at elbow & severe injury to leg',
 'Lacerations to  arm',
 'Details unknown, possibly a PROVOKED INCIDENT',
 ' FATAL. Shark bite was minor injury, but he suffered a heart attack afterwards and died 6 hours later',
 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 'Arms & legs severed',
 'FATAL, but shark involvement not confirmed',
 'No injury to occupants; oar & rudder bitten',
 'Body not recovered. 3 days later some of his equipment was found on seabed appeared damaged by a shark ',
 'No injury, shark slammed into boat',
 'Disappeared whiile swimming alone, body parts recovered, but shark involvement prior to death unconfirmed',
 'Severe injuries to head, neck, shoulder & upper left arm',
 'Tiny cuts & bruises on neck  ',
 '4 irregular lacerated wounds on right arm',
 'Left leg severely lacerated, superficial lacerations of right leg,  board damaged',
 'Right lower leg bitten & defense wounds to hand',
 'Calf lacerated. He was rescued by German submarine, which sunk. Rescued by Italian submarine, which sunk. Managed to reach Dakar',
 'Bruises & minor cuts',
 'FATAL, left thigh & knee bitten ',
 'Lacerations to arms',
 'No injury to occupants, toothmarks on bottom & side of dinghy',
 'Hand lacerated by speared shark PROVOKED INCIDENT',
 'Lacerations and puncture wounds to right foot',
 'Minor injury to right hand & thigh',
 'Right Leg bitten',
 'Laceration to left thigh & left hand',
 'Fingers lacerated',
 'Lacerations to lower leg & foot',
 'Minor injury to hand by hooked shark   PROVOKED INCIDENT',
 'Hooked shark bit stern  PROVOKED INCIDENT',
 'No injury to occupants, shark shook boat "stem to stern"',
 '3 fingers severed when he used his hand as bait',
 'Body recovered  from shark but death due to shark bite was not confirmed',
 "Speared shark bit Davy's ankle &  Pierpont's right leg  PROVOKED INCIDENT",
 'Minor cuts to foot',
 'Lacerations to 3 fingers of left hand ',

In [48]:
# Check age column values

list(df["Age"].value_counts().index)

['17',
 '18',
 '19',
 '20',
 '15',
 '16',
 '21',
 '22',
 '24',
 '25',
 '14',
 '13',
 '23',
 '26',
 '27',
 '28',
 '29',
 '30',
 '12',
 '32',
 '35',
 '10',
 '40',
 '31',
 '38',
 '34',
 '43',
 '36',
 '33',
 '39',
 '37',
 '42',
 '11',
 '9',
 '52',
 '41',
 '50',
 '45',
 '44',
 '47',
 '8',
 '49',
 '46',
 '48',
 '7',
 '55',
 '51',
 '57',
 '6',
 '60',
 '54',
 '53',
 '58',
 '59',
 '61',
 '63',
 '56',
 '62',
 'Teen',
 '69',
 '30s',
 '5',
 '70',
 '68',
 '20s',
 'teen',
 '65',
 '64',
 '3',
 '77',
 '71',
 '66',
 'young',
 '74',
 '7 or 8',
 'F',
 '75',
 ' ',
 '50s',
 '1',
 '8 or 10',
 '40s',
 '78',
 '73',
 '10 or 12',
 '33 & 37',
 '9 or 10',
 'mid-20s',
 'Elderly',
 '84',
 '20?',
 'mid-30s',
 'M',
 '86',
 '32 & 30',
 '  ',
 'Teens',
 '21, 34,24 & 35',
 '13 or 14',
 'X',
 '23 & 26',
 '>50',
 'adult',
 '46 & 34',
 '81',
 '"young"',
 '33 & 26',
 '33 or 37',
 '16 to 18',
 '"middle-age"',
 '7      &    31',
 '18 or 20',
 '28 & 26',
 '21 or 26',
 '36 & 23',
 '28, 23 & 30',
 '87',
 '2 to 3 months',
 '21 & ?',
 '2�',
 '30 & 32',
 '67',
 '25 to 35',
 'MAKE LINE GREEN',
 '9 months',
 '17 & 35',
 '18 to 22',
 '23 & 20',
 'A.M.',
 '18 months',
 '30 or 36',
 '37, 67, 35, 27,  ? & 27',
 '72',
 '60s',
 '36 & 26',
 'Both 11',
 '9 & 12',
 '25 or 28',
 '� ',
 '31 or 33',
 '34 & 19',
 '? & 19',
 "60's",
 '17 & 16',
 '?    &   14',
 '13 or 18',
 '(adult)',
 '12 or 13',
 'Ca. 33',
 '50 & 30',
 '6�']

In [49]:
# Objective: keep first instance of repeating digits. For pre-cleaning, remove every string with months value

df.loc[df["Age"].str.contains("month").fillna(False), ["Age"]] = np.nan

In [50]:
# Look at structure of age column

list(df["Age"].value_counts().index)

['17',
 '18',
 '19',
 '20',
 '15',
 '16',
 '21',
 '22',
 '24',
 '25',
 '14',
 '13',
 '26',
 '23',
 '27',
 '28',
 '29',
 '30',
 '12',
 '35',
 '32',
 '10',
 '31',
 '40',
 '38',
 '34',
 '43',
 '36',
 '33',
 '37',
 '39',
 '42',
 '9',
 '11',
 '41',
 '52',
 '45',
 '50',
 '44',
 '47',
 '49',
 '8',
 '48',
 '46',
 '7',
 '55',
 '51',
 '60',
 '6',
 '57',
 '54',
 '53',
 '58',
 '59',
 '61',
 '56',
 '63',
 '69',
 'Teen',
 '62',
 '5',
 '30s',
 '68',
 '70',
 '20s',
 'teen',
 '64',
 '3',
 '65',
 '66',
 '71',
 '77',
 ' ',
 '7 or 8',
 'F',
 '75',
 '40s',
 'young',
 '1',
 '8 or 10',
 '78',
 '50s',
 '74',
 '10 or 12',
 'mid-20s',
 '21, 34,24 & 35',
 '20?',
 'Elderly',
 'mid-30s',
 '32 & 30',
 '84',
 '  ',
 '73',
 'X',
 'Teens',
 '>50',
 '13 or 14',
 '23 & 26',
 '86',
 'M',
 '33 & 37',
 '9 or 10',
 '46 & 34',
 'adult',
 '34 & 19',
 '87',
 '18 to 22',
 '33 & 26',
 '33 or 37',
 '16 to 18',
 '"middle-age"',
 '7      &    31',
 '18 or 20',
 '28 & 26',
 '36 & 23',
 '"young"',
 '28, 23 & 30',
 '21 & ?',
 '2�',
 '30 & 32',
 '67',
 '25 to 35',
 'MAKE LINE GREEN',
 '17 & 35',
 '23 & 20',
 '50 & 30',
 '81',
 'Ca. 33',
 'A.M.',
 '30 or 36',
 '37, 67, 35, 27,  ? & 27',
 '72',
 '60s',
 '36 & 26',
 'Both 11',
 '9 & 12',
 '25 or 28',
 '� ',
 '21 or 26',
 '31 or 33',
 '? & 19',
 '17 & 16',
 '6�',
 '?    &   14',
 '13 or 18',
 '(adult)',
 '12 or 13',
 "60's"]

In [51]:
# for every age row without na, create new Age row containing the first instance of consecutive digits

df["newAge"] = 1
df.loc[~df["Age"].isna() , ["newAge"]] = df['Age'].str.extract(r"([0-9]+)", expand=False)

In [52]:
# Check for new Age value counts

df['newAge'].value_counts()

1     2684
17     150
18     147
20     144
19     139
      ...
87       1
67       1
2        1
86       1
84       1
Name: newAge, Length: 81, dtype: int64

In [53]:
# Compare value count lists

print(list(df['newAge'].value_counts().index))
print(list(df['Age'].value_counts().index))

[1, '17', '18', '20', '19', '16', '15', '21', '22', '25', '24', '14', '13', '30', '23', '26', '28', '27', '29', '12', '32', '35', '40', '10', '31', '38', '34', '33', '43', '36', '37', '9', '39', '42', '11', '50', '41', '52', '45', '8', '44', '47', '49', '46', '48', '7', '55', '51', '60', '6', '57', '54', '53', '58', '61', '59', '63', '56', '69', '62', '5', '70', '68', '3', '65', '64', '71', '77', '66', '75', '74', '1', '78', '73', '81', '72', '87', '67', '2', '86', '84']
['17', '18', '19', '20', '15', '16', '21', '22', '24', '25', '14', '13', '26', '23', '27', '28', '29', '30', '12', '35', '32', '10', '31', '40', '38', '34', '43', '36', '33', '37', '39', '42', '9', '11', '41', '52', '45', '50', '44', '47', '49', '8', '48', '46', '7', '55', '51', '60', '6', '57', '54', '53', '58', '59', '61', '56', '63', '69', 'Teen', '62', '5', '30s', '68', '70', '20s', 'teen', '64', '3', '65', '66', '71', '77', ' ', '7 or 8', 'F', '75', '40s', 'young', '1', '8 or 10', '78', '50s', '74', '10 or 12', 'mid-20s', '21, 34,24 & 35', '20?', 'Elderly', 'mid-30s', '32 & 30', '84', '  ', '73', 'X', 'Teens', '>50', '13 or 14', '23 & 26', '86', 'M', '33 & 37', '9 or 10', '46 & 34', 'adult', '34 & 19', '87', '18 to 22', '33 & 26', '33 or 37', '16 to 18', '"middle-age"', '7      &    31', '18 or 20', '28 & 26', '36 & 23', '"young"', '28, 23 & 30', '21 & ?', '2�', '30 & 32', '67', '25 to 35', 'MAKE LINE GREEN', '17 & 35', '23 & 20', '50 & 30', '81', 'Ca. 33', 'A.M.', '30 or 36', '37, 67, 35, 27,  ? & 27', '72', '60s', '36 & 26', 'Both 11', '9 & 12', '25 or 28', '� ', '21 or 26', '31 or 33', '? & 19', '17 & 16', '6�', '?    &   14', '13 or 18', '(adult)', '12 or 13', "60's"]

In [54]:
# Check again

df[['newAge','Age']].dropna()

     newAge       Age
0        16        16
2        43        43
6        60       60s
7        51        51
8        50        50
...     ...       ...
5933     16        16
5944     50        50
5955     13  13 or 14
5966     16        16
5991     15        15

[3276 rows x 2 columns]

In [55]:
## Fatal column. Rename and make binary

df = df.rename(columns={"Fatal (Y/N)":"Fatal"})

In [56]:
# Check Fatal column value names

df["Fatal"].value_counts()

N          4314
Y          1552
UNKNOWN      94
 N            8
#VALUE!       1
F             1
n             1
N             1
Name: Fatal, dtype: int64

In [57]:
# make Sex column to only M and F
df.loc[df["Fatal"] == " N", ["Fatal"]] = "N"
df.loc[df["Fatal"] == "N ", ["Fatal"]] = "N"
df.loc[df["Fatal"] == "n", ["Fatal"]] = "N"
df.loc[df["Fatal"] == "F", ["Fatal"]] = "UNKNOWN"
df.loc[df["Fatal"] == "#VALUE!", ["Fatal"]] = "UNKNOWN"

# convert UNKNOWN into NaN
df.loc[df["Fatal"] == "UNKNOWN", ["Fatal"]] = np.nan

# Convert into binary
df.loc[df["Fatal"] == "N", ["Fatal"]] = 0
df.loc[df["Fatal"] == "Y", ["Fatal"]] = 1

In [58]:
# Confirm new Fatal column structure

df["Fatal"].value_counts()

0    4324
1    1552
Name: Fatal, dtype: int64

In [59]:
## Check time column

list(df["Time"].value_counts().index)

df["nTime"] = 1
# Just convert first occurence of digits followed by h into hour
df.loc[~df["Time"].isna() , ["nTime"]] = df['Time'].str.extract(r"([0-9]+)[h]", expand=False)

In [60]:
# Check 

df[['nTime','Time']].dropna()

     nTime         Time
0       13        13h00
2       10        10h43
6       15        15h15
7       14        14h30
8       15        15h40
...    ...          ...
5782    14        14h00
5804    17  17h00-18h00
5811    19  19h00-20h00
5824    13        13h00
5890    18        18h00

[2234 rows x 2 columns]

In [61]:
# Rename into time_hours

df = df.rename(columns={"nTime":"time_hours"})

In [62]:
# Remove trailing whitespace in Species column name

df = df.rename(columns={"Species ":"Species"})

In [63]:
# Check out species column

list(df["Species"].value_counts().index)

['White shark',
 'Shark involvement not confirmed',
 'Tiger shark',
 'Bull shark',
 "6' shark",
 "4' shark",
 "1.8 m [6'] shark",
 "1.5 m [5'] shark",
 "1.2 m [4'] shark",
 "3' shark",
 "5' shark",
 "4' to 5' shark",
 "3 m [10'] shark",
 '2 m shark',
 'No shark involvement',
 'Wobbegong shark',
 "3' to 4' shark",
 '3 m shark',
 "2.4 m [8'] shark",
 "3.7 m [12'] shark",
 "12' shark",
 'Blue shark',
 'Blacktip shark',
 'Mako shark',
 "1.2 m to 1.5 m [4' to 5'] shark",
 "7' shark",
 '"a small shark"',
 "5 m [16.5'] white shark",
 "10' shark",
 '1.5 m shark',
 "4 m [13'] white shark",
 'Raggedtooth shark',
 'Zambesi shark',
 'Bronze whaler shark',
 "6 m [20'] white shark",
 'Grey nurse shark',
 'Nurse shark',
 "3 m [10'] white shark",
 '1 m shark',
 "White shark, 4 m [13'] ",
 "2.1 m [7'] shark",
 "2' to 3' shark",
 'a small shark',
 'Hammerhead shark',
 '"small shark"',
 'Unidentified species',
 '2.5 m shark',
 "9' shark",
 'Sandtiger shark',
 'Basking shark',
 'Lemon shark',
 "Bull shark, 6'",
 "2.5 m [8.25'] white shark",
 "5.5 m [18'] shark",
 ' ',
 "White shark, 5 m [16.5'] ",
 "4 m to 5 m [13' to 16.5'] white shark",
 "14' shark",
 "6' to 8' shark",
 "15' shark",
 'Tiger shark?',
 '1.8 m shark',
 'Thought to involve a Zambesi shark',
 "White shark, 3 m [10'] ",
 'Spinner shark',
 "0.9 m [3'] shark",
 "8' shark",
 "4.3 m [14'] shark",
 "4 m [13'] shark",
 "5 m to 6 m [16.5' to 20'] white shark",
 'Shark involvement prior to death not confirmed',
 "5' to 6' shark",
 'Oceanic whitetip shark',
 "5.5 m [18'] white shark",
 'Possibly a juvenile blacktip or spinner shark',
 "Tiger shark, 3 m [10']",
 "2' shark",
 "1.8 m to 2.4 m [6' to 8'] shark",
 'Blacktip or spinner shark',
 "13' shark",
 "1.8 m [6'] blacktip shark",
 "3 m [10'] bull shark",
 '"sand shark"',
 "4.6 m [15'] shark",
 'Angel shark',
 "White shark, 3.7 m [12'] ",
 "2 m [6.75'] shark",
 '2 m [6\'9"] shark',
 'blacktip or spinner shark',
 'Sevengill shark',
 "1.5 m to 1.8 m [5' to 6'] shark",
 "Tiger shark, 2.4 m [8']",
 "Tiger shark, 1.8 m to 2.4 m [6' to 8'] ",
 "12' to 14' shark",
 '2m shark',
 '4 m shark',
 "Tiger shark, 14' ",
 "White shark, 2.4 m [8'] ",
 "2.7 m [9'] shark",
 "4' to 6' shark",
 '2 sharks',
 'Thought to involve a white shark',
 'small shark',
 'White shark?',
 'Grey reef shark',
 "Bronze whaler shark, 6'",
 '4 m white shark',
 "3 m to 4 m [10' to 13'] white shark",
 "6 m [20'] shark",
 'Galapagos shark',
 'Unidentified',
 '18" to 24" shark',
 'reef shark?',
 "16' shark",
 "3' to 5' shark",
 "Lemon shark, 4'",
 'juvenile shark',
 "Bronze whaler shark, 3 m [10'] ",
 "Nurse shark, 1.5 m [5'] ",
 'Caribbean reef shark',
 '3 sharks',
 "a small shark'",
 '5 m shark',
 "White shark, 15'",
 "3.5' to 4' shark",
 'White shark, 3m to 4m',
 'Shark involvement prior to death was not confirmed',
 "10' to 12' shark",
 'White shark, 4m',
 '4.5 m white shark',
 "Bronze whaler shark, 2.5 m [8.25'] ",
 'Blue pointer',
 "20' shark",
 'White shark, 5m',
 '3 m white shark',
 'Bronze whaler shark?',
 "Tiger shark, 3.7 m [12'] ",
 '"a dog shark"',
 "Tiger shark, 10' to 12' ",
 'Tiger shark, 3 m ',
 "Tiger shark, 1.8 m [6'] ",
 'White shark, 4.5 m ',
 "Blacktip shark, 4'",
 "Tiger shark, 1.8 m [6']",
 '2 m to 3 m shark',
 '"small sharks"',
 "Tiger shark, 2.4 m to 3 m [8' to 10'] ",
 '3.5 m white shark',
 "2.3 m [7'] shark",
 "18' shark",
 "2.4 m [8']  shark",
 "Tiger shark, 5 m [16.5']",
 'White sharks',
 'Bull shark suspected due to freshwater habitat',
 '7-gill shark',
 '6 m shark',
 "White shark, 4 m to 5 m [13' to 16.5'] ",
 'bull shark',
 'Bull or tiger shark',
 'A pack of 6 sharks',
 '"sand" shark',
 "Said to involve a 7 m [23'] white shark",
 "Mako shark, 4.3 m [14']",
 '3.6 m [11\'9"] white shark',
 "Tiger shark, 2.5 m [8.25']",
 'Thought to involve a tiger shark',
 'Bronze whaler shark, 1.5 m ',
 "Raggedtooth shark, 2.5 m [8.25'] ",
 'Bronze whaler shark, 1.5m',
 "1.2 m [4'] bull shark",
 "Grey reef shark, 1.2 m [4'] ",
 'Possibly a sand shark',
 "Raggedtooth shark, 1.5 m [5'] ",
 'small nurse shark',
 "Sharks averaged 1.8 m [6'] in length",
 'Dusky shark, 1 m ',
 'White shark, 3.5 m',
 "Tiger shark, 8' to 9' ",
 'small blacktip shark?',
 "Tiger shark, 7'",
 "Tiger shark, 10' to 12'",
 "Bull shark, 1.8 m to 2.1 m [6' to 7'] ",
 'Possibly C. leucas',
 "Tiger shark, 10' ",
 "Bull shark, 5'",
 "White shark, 5.5 m [18']",
 "1.5 m [5'] blacktip shark",
 'White shark, according to witnesses',
 "Tiger shark, 3.7 m [12']",
 'Whale shark',
 "Tiger shark, 12'",
 'Possibly a bull shark',
 'Blacktip reef shark ',
 "Nurse shark, 1.2 m [4'] ",
 "1.8 m to 2.1 m [6' to 7'] shark",
 'Wobbegong shark?',
 'Bull shark, 1.5m ',
 'Tiger shark, 4 m ',
 "Thought to involve a 2.6 m [8.5'] white shark",
 "2.5 m [8.25'] shark",
 '"a large shark"',
 "White shark, 10' to 12' ",
 "6 m [20']  shark",
 'Bull shark, 3.5 m',
 'Carpet shark',
 'Tiger shark, 300-kg [662-lb] ',
 "White shark, 10'",
 "2 m [6.75'] white shark",
 "Tiger shark, 2.4 m 3.4 m [8' to 11']  ",
 "White shark, 12' ",
 "5.5 m to 6 m [18' to 20']  white shark",
 "5.5 m to 6 m [18' to 20'] white shark",
 "3.5 m [11.5'] white shark",
 'Raggedtooth shark, 1 m ',
 "White shark, 8' to 10'",
 "Tiger shark, 10'",
 "Tiger shark, 1.5 m [5']k",
 "Tiger shark, 4.3 m [14'] ",
 "0.9 m to 1.2 m [3' to 4'] shark",
 '200-lb shark',
 'White shark, 2.5 m ',
 'White shark, 6 m',
 "1.8 m to 2.4 m [6' to 8'] hammerhead shark",
 'Possibly a bull shark or tiger shark',
 "White shark, 5.5 m [18'] ",
 "1.8 m [6'], 180-lb shark",
 "Bull shark, 7'",
 "3 m to 5 m [10' to 16.5'] white shark",
 "Tiger shark, 3 m [10'] ",
 "Nurse shark, 2.5' ",
 'Shark involvement questionable',
 "Tiger shark, 1.5 m to 1.8 m [5' to 6'] ",
 'Raggedtooth shark ',
 "1.2 m  [4'] shark",
 "Raggedtooth shark, 1.2 m [4'] ",
 "Said to be a 7.6 m [25'] shark",
 'Shark involvement unconfirmed',
 'Nurse shark, 1 m ',
 'White shark, 2.5m ',
 "Tiger shark, 15'",
 "White shark, 2.7 m [9'] ",
 "White shark, 4.9 m [16'] ",
 '1m shark',
 "3'  shark",
 'Zambesi shark?',
 "0.9 m to 1.5 m [3' to 5'] shark",
 'White shark, 3 m ',
 "White shark, 11' to 12'",
 'White shark, 5 m ',
 'Tiger shark, 3m ',
 'A large white shark was filmed by divers on a local wreck 2 days prior to the incident.',
 'Bull shark, 3m',
 "2 m to 2.5 m [6.75'  to 8.25'] shark",
 'A �small� shark',
 "1.5 m [5'] Caribbean reef shark",
 "White shark, 5.5 m to 6 m [18' to 20'] ",
 '"A small shark"',
 "Tiger shark, 6'",
 'Nurse shark, 58", 34-lb ',
 'White shark, 2m',
 'Possibly a spinner shark',
 "8' blue shark",
 'Questionable incident',
 '2 to 2.5 m shark',
 'Salmon shark',
 'Sand shark',
 'Oceanic whitetip shark, 2.5m, female',
 'Juvenile dusky shark',
 '5 m white shark',
 "1.8 m [6'] grey reef shark",
 'White shark named �Spotty�',
 'Shark involvement suspected but not confirmed',
 'Reported to involve a hammerhead shark',
 'Bull shark?',
 "Grey nurse shark, 2.4 m [8'] ",
 'Shark involvement not cofirmed',
 "Wobbegong shark, 1.8 m [6'] ",
 "4.5' shark",
 'Grey nurse shark?',
 "1.5 m [5'] shark, probable bull shark",
 "Tiger shark, 14'",
 "White shark, 5 m to 6 m [16.5 to 20'] ",
 "Wobbegong shark, 1.2 m [4'] ",
 '1.8 m blacktip "reef" shark',
 '2.5 to 3 m shark',
 "Grey nurse shark, 1.8 m [6']",
 'White shark, 3 m',
 'Thought to involve a bull shark',
 '3.5 m shark',
 "White shark, 2.4 m to 3 m [8' to 10'] ",
 '� ',
 'Blacktip Reef shark ',
 "Grey nurse shark, 10' ",
 "8' to 10' shark",
 "Tiger shark, 10'  ",
 'Possibly a bronze whaler shark',
 'small blacktip shark',
 'Shark involvement probable',
 "1.8 m [6'] shark ",
 "Tiger shark, 1.5 m [5'] ",
 '2 m hammerhead',
 "Blacktip shark, 5'",
 'White shark, 3.6 m [11\'9"] ',
 "Sandtiger shark, 2.1 m [7'] ",
 'Bull shark, 2m',
 "3.5 m [11.5'] shark",
 "1.2 m [4'] blacktip shark",
 'White shark (tooth fragment recovered)',
 "Blacktip shark, 4' to 5'",
 'Shark involvement doubtful',
 "3 m to 4 m [10' to 13']  white shark",
 "Bull shark, 8'",
 'Tiger shark, 1.5 m ',
 'small sharks',
 'reef shark',
 "Nurse shark, 2.1 m [7']",
 '20 to 30kg shark',
 'White shark, 15\'2" ',
 "4.9 m [16'] shark",
 "White shark, 4.6 m [15'] ",
 "1.5 m to 2 m [5' to 6.75'] shark",
 'Bronze whaler',
 "Mako shark, 2 m [6.75'] ",
 'Grey nurse shark, 3m',
 'White shark, 2.5m',
 "Bull shark, 4' to 5' ",
 "Mako shark, 1.5 m [5'] ",
 'Shark involvement  questionable',
 'shark involvement not confirmed',
 '3 m to 4 m shark',
 'Allegedly a 33-foot shark',
 '2 m to  3 m shark',
 "1.8 m [6'] carpet shark",
 "Tiger shark, 3.7 m to 4.3 m  [12' to 14']",
 "numerous dusky sharks & a 3 m to 4.6 m [10' to 15'] to  tiger shark",
 "Possibly a 6' lemon shark",
 '>1.6 m shark',
 'White shark or thresher shark',
 'C. macrurus captured 48 hours after attack with tissue removed from man in its gut; species identified by G.P. Whitley,  reported as C. obscurus by  R. Steel',
 "Bull shark, 2.3 m [7.5'] ",
 'Bronze whaler shark, a  juvenile ',
 "White shark, 12' to 15' female",
 '�small brown shark�',
 "14' to 16' white shark",
 "Tiger sharks, 2.4 m to 4.9 m [8' to 16'] ",
 '2.5 oceanic whitetip shark',
 'Allegedly a 4 m tiger shark',
 "Horn shar,k Heterodontus francisci, 1.2 m [4'] ",
 'Bull shark, 1.3 m',
 'Blacktip shark, 2m',
 'A hammerhead shark, then 8 to 10 other sharks were said to be  involved',
 "Oceanic whitetip shark, 6'",
 "Bronze whaler shark, 4.6 m [15'] ",
 "6' blacktip shark",
 "According to Carlsmith, the shark's mouth was 3' wide",
 "Mako shark, 14' ",
 'Remains recovered 5 days later',
 "Grey nurse shark, 4' ",
 '1.8 m silky shark',
 'Blue shark bites present ',
 "White shark, 1.8 m to 2.1 m [6' to 7']  according to Shreuder and a witness",
 'Survivors said 2 species of sharks were involved:  oceanic whitetip sharks and another species',
 "Caribbean reef shark, 1.2 m to 1.5 m [4' to 5'] ",
 '"Blue nose sharks"',
 "3.5 m [11.5'], 510-kg [1125-lb] hooked & shot white shark",
 "Shovelnose shark, 6 m [20'] ",
 "Spinner shark, 6'",
 "3' blacktip shark",
 '2\' "banjo shark"',
 "2.4 m [8'] tiger shark caught 40 hours later with shorts of the boy in its gut",
 'Bonita sharkk, 200-lb',
 '3 bull sharks',
 "14' white shark",
 "4.3 m [14'] shark seen in vicinity",
 '250-lb "dog shark"',
 "12' tiger shark",
 'Small bull shark',
 'Lemon shark, 2.5m to 3m ',
 'Wobbegong shark, 1.4 m [4\'6"] ',
 '40-lb sand shark',
 "White shark, 6 m [20']",
 'a small hammerhead shark',
 "4' shark?",
 'Nurse shark?',
 "4m [13'] shark",
 'Questionable incident; reported as shark attack but thought to involve a pinniped instead ',
 "Blacktip shark, 1.2 m to 1.8 m [4' to 6'] ",
 "2.1 m [7'] sandtiger shark",
 "Bronze whaler shark,3.7 m [12'] ",
 'White shark, 4.5 m  to 6 m [14\'9" to 20\'] according to witnesses',
 'Bronze whaler shark, 4m',
 "Raggedtooth shark, 3.5 m [11.5'] ",
 '3- to 4-foot shark',
 "Said to involve a 6.5 m [21.5'] shark",
 "Oceanic whitetip shark,1.8 m [6'] ",
 "Wobbegong shark, 3' ",
 "Tiger shark, 2.4 m to 2.7 m [8' to 9']  ",
 "White shark, 5' k",
 '5m shark',
 " white shark, 15' ",
 'Said to involve 2 sharks',
 '1.8 m to 2.4 m [6\' to 8\'] "black finned shark"',
 "White shark, 2.1 m [7']  based on tooth pattern",
 "2 m [6.75'] sevengill  shark",
 'Possibly a blacktip reef shark',
 '2.4 m shark',
 '1.5 m [5\'] "whaler shark"',
 "Shortfin mako shark, 3 m to 3.4 m [10' to 11'] ",
 '1.8 to 2 m C. albimarginatus',
 'Wobbegongs',
 "2.7 m to 3 m [9' to 10'] sharks",
 'Soupfin shark',
 'Tiger shark, 4.8 m',
 'Blue shark?',
 '6 m, 600-kg shark',
 "1.8 m to 2.1 m [6' to 7'] hammerhead shark",
 '7-gill shark?',
 '1.3 m [4\'3"] shark',
 "2.1 m [7'] shark, possibly a spinner shark",
 "White shark, 3.8 m [12.5']  ",
 '4.5 m shark',
 '300-kg [662-lb] shark',
 "2.4 m to 3 m [8' to 10'] white shark",
 'Shark involvement prior to death still to be determined',
 "Tiger shark, 2.7m  [9']",
 'possibly a bronze whaler shark',
 "106 cm [3.5']  shark",
 "Whaler shark, 2.7 m [9'], 350- to 450-lb  identified by G.P. Whitley",
 'Raggedtooth shark, 147-kg [324-lb] ',
 'Shark was said to �have a very rough ��-thick skin�',
 "White shark, 1.8 m [6'] ",
 "Blue shark, 1.8 m [6'] ",
 'White shark, 2.7 m [9\'1"], 750-lb ',
 'Grey reef shark, Identified as C. menisorrah, by E.S. Hobson, F. Mautin & E.S. Reese (1961)',
 "1.7 m [5.5'] shark",
 'Thought to involve a porbeagle or mako shark',
 '1.2 m to 1.5 m [4\' to 5\'] "reef shark"',
 '1.6 m shark',
 'Tiger shark, 2.5 m',
 "1.2 m to 1.5 m [4' to 5'] shark, possibly a bull shark",
 'White shark, 4m ',
 '1.5 m copper shark',
 "Reef shark, 5'",
 '2 to 3 m shark',
 "Mako shark, 1.8 m [6']",
 '2 m cow shark',
 "Blacktip shark, 2.4 m to 3 m [8' to 10'] ",
 'White shark (tooth fragments recovered)',
 '8; 206-lb shark',
 "5' to 6' spinner or bull shark",
 "4.5 m to 5.5 m [15' to 18'] white shark",
 ' Tiger shark, 2.8m',
 "2.3 m [7.5'] white shark, identified by M. Smale",
 'Tiger shark,  3.6 m [11\'9"], 850-kg [1874-lb] female, contained Girvan\'s remains ',
 "Sandtiger shark, 3 m [10'] ",
 "5 m  [16.5'] white shark",
 'Remains recovered from shark caught days later',
 "[4.5' to 5'] shark",
 '"A pack of 6 sharks"',
 '2.1 m [7\'] shark with "a very flat head� that had followed the boat for 3 days',
 "Mako shark, 1.8 m [6']  ",
 "2.7 m [9'] bull shark, identified by Capt. W. Gray",
 'Tiger shark, 10?',
 '1.7 m shark',
 'White shark, 6.5 m ',
 "Carpet shark, 1.5 m [5']",
 "Nurse shark, 6'",
 'White shark, 4.8 m ',
 "Nurse shark, 60 cm to 90 cm [2' to 3'] ",
 '<1.5 m shark',
 'Tiger shark & others',
 'Hammerhead shark?+O2356',
 "1.2 m to 1.5 m [4' to 5'] hammerhead shark",
 "Sandbar shark ,8'",
 "Nurse shark, 4'",
 "White shark, 12' to 14'",
 'Though to involve a white shark',
 "Blue pointer, 11' ",
 "1' to 2' hammerhead or bonnethed shark",
 "1.8 m [6'] blacktip shark or spinner shark",
 "Tiger shark, 13' ",
 'Possibly  a blacktip or spinner shark',
 'Survivors said 2 species of sharks were involved:  oceanic whitetip sharks and another species,',
 'said to involve a tiger shark',
 'Bull shark, 8',
 'Mako shark, 125-lb ',
 "12' to 14' white shark",
 "Tiger shark, 12' ",
 "Zambesi shark, 1.7 m [5.5'] ",
 "2.5 m [8.25'] white shark ",
 "Nurse shark, 1.1 m [3.5'] ",
 '100-kg [221-lb] dead blue shark',
 "2.7 m [9']shark",
 'Cookie cutter shark',
 'white shark',
 "Sevengill shark, 2.4 m [8'] ",
 "1.5 m [5'] white shark or sevengill shark",
 'Possibly a broadnose 7-gill shark',
 'Shortfin mako shark, 175-lb ',
 'Shark involvement not confirmed, injury may have been caused by a bluefish',
 '"Attacked by a number of sharks"',
 "3.7 m [12'], 1200-lb shark. Shark caught & its jaw exhibited at the Carnegie Museum",
 "Wobbegong shark, 1.4 m [4.6'] ",
 'Broadnose sevengill shark',
 "4 m [13'], 590-kg white shark",
 'Said to be a �small shark�',
 'White shark, 1,900-lb ',
 'Mako shark, 100-kg [221-lb] ',
 "Mako shark, 3 m [10']",
 "5.5 m [18'] shark seen in the vicinity",
 'White shark, 2.7 m',
 "Raggedtooth shark, 2.7 m [9'] ",
 "Tiger shark, 4 m [13'] ?",
 "Bronze whaler shark, 1.8 m [6'] ",
 "+3' shark",
 'Spinner or blacktip sharks',
 'White shark, 2.8 to 3 m ',
 'Shovel-nosed guitarfish',
 'Reported to involve a 4 m white shark',
 '2 m [6\'9"] shark ',
 '"grey-colored shark"',
 'A 6.5\' "blue-nosed shark"',
 "3.5' hammerhead shark",
 "Bull shark, 6' to 7'",
 "Bull shark, 9' to 10'",
 "3 m [10'] blue whaler",
 "Tiger shark, 4 m to 4.3 m [13' to 14'] ",
 'Hand found in gut of 2.9 m to 3.3 m [9\'7" to 10\'11"] Galapagos shark, C. galapagensis',
 "3' small spotted catshark, Scyliorhinus canicula",
 '5 m to 6 m white shark',
 'Tooth fragments of �whaler� shark were recovered, a bull shark, according to Edwards',
 "60 cm to 90 cm [2' to 3'] shark",
 "Said to involve a Grey nurse shark 3.7 m [12'] ",
 'Bull shark, 2m ',
 'Raggedtooth shark, 2 m [6\'9"], 5-year-old, captive female ',
 'White shark, 2 m [6\'9"]  (Tooth fragment recovered from victim\'s shoulder & identified by J.T. Nicholls)',
 'Gray reef shark',
 '"small brown-colored shark"',
 "Shortfin mako shark, 2.3 m [7.5'] ",
 '18" to 36" shark',
 "2.1 m [7'] shark, a shark's serrated tooth recovered from toe",
 'Raggedtooth shark, 2 m ',
 'Raggedtooth shark, 2m',
 'Species unidentified',
 'Tiger shark, 4.5 to 5.5 m [14\'9" to 18\'], 2000-lb  ',
 "Porbeagle shark, 3 m [10']rk",
 'small carpet shark',
 "1' to 2' shark",
 '440-lb shark',
 "Bull shark, 5' ",
 'Tiger shark, 3.7 m to 4.5 m [12\' to 14\'9"]  ',
 'Mako shark, 3m',
 'sandtiger shark',
 "Bronze whaler shark,  3m [10'] ",
 ">1.8 m [6'] shark",
 '250-lb female "blue fin" shark',
 ">2.4 m [8'] shark",
 "White shark, 12' to 15' ",
 'Possibly a sandbar shark or small blacktip shark',
 'Salmon shark suspected, but unlikely',
 'sand shark',
 "1.5 m [5'] shark, either a bronze whaler or a grey nurse shark",
 "1.5 m to 2 m [5' to 6.75'] Caribbean reef shark ",
 '"sandshark"',
 'Zambezi shark (tooth fragments recovered)',
 "White shark, 14' to 16' ",
 "White shark, 1.5 m [5'] k",
 'Small shark',
 '43" shark',
 'Bronze whaler shark, 3 m',
 'Tiger sharks & bull sharks (20 sharks in all)',
 "18', 750-lb shark",
 "1.5 m to 2.1 m  [5' to 7'] shark",
 'Bronze whaler shark, 3.5 m ',
 "2.4 m [8'] white shark, species identity confirmed by witnesses & tooth pattern in surfboard",
 '2.8 m [9\'3"] white shark',
 "Bronze whaler shark, 10' ",
 'Thought to involve a 1.2 to 1.5 m tubar�o da gralha preta -  a blacktip shark, C. limbatus?',
 'A bull shark, according to some of the divers on the boat',
 '"reef shark"',
 "9.5' shark?",
 "Tiger shark, 6' ",
 'White shark, 3m, seen in area and hooked 3 days later',
 'Thought to involve a small sand shark',
 '9-foot shark',
 "1.2 m [4'], possibly  larger shark",
 'Raggedtooth shark, 56-kg [123-lb] ',
 'Possibly a hammerhead shark',
 "Silky shark, 1.9 m [6.5']",
 'Tiger shark, 2.5 m ',
 '4.9 m white shark',
 "Hammerhead shark, 5' ",
 "2.4 m [8'], 600-lb shark",
 "On 11-Jan-1994, his remains washed ashore. A 2.4 m [8'] tiger shark thought to be involved",
 "Wobbegong shark, 4'",
 'White shark, 2000-lb',
 "Alleged to involve a White shark, 7.6 m [25'] ",
 'Unknown',
 'Sandbar shark',
 'White shark according to tooth pattern and witnesses',
 'Mako shark, 1.3 m gaffed ',
 'Said to involve a 1.5 m shark',
 'White shark (identified by Dr. Hugh Smith) ',
 "White shark,4.6 m [15'] ",
 'Mako shark, 2.3 m, 150-kg  ',
 "Remains recovered from 5.5 m [18'] white shark",
 '>1 m shark',
 '40 to 50 sharks attacked survivors in the water',
 "1.8 m [6'] reef shark - or a 2.1 m to 2.4 m [7' to 8'] grey-colored shark",
 'Tooth fragments recovered from hull',
 "Reported to involve a White shark, 6 m to 7m [20' to 23'] ",
 'Spinner shark or blacktip shark',
 '80-lb hooked shark',
 "6' to 8' bull shark",
 '1 m shark, possibly whitetip reef shark',
 ">6 m [20'] white shark",
 "A 2' shark was seen in the area by witnesses",
 '"Dog shark"',
 "0.9 m  [3'] shark",
 "Bull shark, 2.4 m [8']",
 'Reported by media as shark attack, but shark involvement prior to death was not confirmed',
 '"a very large shark"',
 'Bull shark, 1.65 m [5\'5"] was speared & killed',
 'Lemon shark, 1.8 m [6\'] male, N. breviostris, identified by W.A. Stark II, later the same day a 6\'8" pregnant female lemon shark bit the bow of the boat',
 "Tiger shark, 8' ",
 '300- to 400-lb Zambesi shark',
 " Tiger shark, 3'",
 '2 white shark: 13\' & 9"8"',
 "1.2 m to 1.8 m [4' to 6'] shark observed in area",
 'White shark, 2 m',
 "5.5' shark",
 "Blue shark, 1.5 m [5'] ",
 'Shark involvement not confirmed; officials considered barracua',
 'Most likely, a small shark',
 'Whitetip reef shark, 1m',
 'Oceanic whitetip shark, 2.5m ',
 '30-kg [66-lb] shark',
 "Tiger shark, 4.6 m to 7.6 m [15' to 25'] ",
 'reef shark, 1.5m',
 "1.5 m [5'] dusky shark",
 'A small spinner shark',
 'Possibly white sharks',
 '5 m to 7 m white shark',
 "1.8 m [6'] Zambezi shark",
 "5.5 m [18'] white shark, identified by witnesses & tooth marks",
 "60 cm to 90 cm [2' to 3'] blacktip or spinner shark",
 "White shark, 3 m [10']rk",
 "Spinner shark, 1.2 m to 1.5 m [4' to 5'] ",

In [64]:
# Convert whole column to lowercase

df["Species"] = df["Species"].str.lower()

In [65]:
# Keep only letters excluding single m

#stop_words = ["thought", "large", "small", "�", "named", "of", "to","lb ", " lb", "m ", " m", "or", "a ", "not","confirmed", "injury", "may", "be", "due", "stringray", "probable", "but", "kg", "possibly", "said", "involve","identity","confirmed", "by", "tooth", "pattern"]
stop_words = [" m ", "m ", "lb"]

df["nSpecies"] = df["Species"]
for i in stop_words:

    df.loc[~df["nSpecies"].isna() , ["nSpecies"]] = df["nSpecies"].str.replace(i,"")

In [66]:
# Remove numbers

df.loc[~df["nSpecies"].isna() , ["nSpecies"]] = df["nSpecies"].str.replace(r"[0-9]+","",regex=True)

In [67]:
# Remove special characters

df.loc[~df["nSpecies"].isna() , ["nSpecies"]] = df["nSpecies"].str.replace(r"[.',?\[\]\"-><]+","",regex=True)

In [68]:
# Remove one and two letter words

df.loc[~df["nSpecies"].isna() , ["nSpecies"]] = df["nSpecies"].str.replace(r"\b[a-zA-Z]{1,2}\b","",regex=True)

In [69]:
# Remove trailing whitespaces

df.loc[~df["nSpecies"].isna() , ["nSpecies"]] = df["nSpecies"].str.strip()

In [70]:
list(df["nSpecies"].value_counts().index)

['shark',
 'white shark',
 'tiger shark',
 'bull shark',
 'shark involvement not confirmed',
 'bronze whaler shark',
 'blacktip shark',
 'nurse shark',
 'small shark',
 'raggedtooth shark',
 'wobbegong shark',
 'mako shark',
 'grey nurse shark',
 'blue shark',
 'hammerhead shark',
 'zambesi shark',
 'lemon shark',
 'shark involvement',
 'sandtiger shark',
 'sand shark',
 'spinner shark',
 'sharks',
 'grey reef shark',
 'reef shark',
 'oceanic whitetip shark',
 'blacktip  spinner shark',
 'caribbean reef shark',
 'blacktip reef shark',
 '',
 'sevengill shark',
 'unidentified species',
 'dusky shark',
 'carpet shark',
 'basking shark',
 'thought  involve  zambesi shark',
 'small sharks',
 'dog shark',
 'blue pointer',
 'copper shark',
 'angel shark',
 'possibly  bull shark',
 'porbeagle shark',
 'juvenile shark',
 'possibly  juvenile blacktip  spinner shark',
 'shark involvement prior  death not confirmed',
 'greycolored shark',
 'gill shark',
 'sandbar shark',
 'small blacktip shark',
 'thought  involve  white shark',
 'shortfin mako shark',
 'whaler shark',
 'galapagos shark',
 'shark seen  vicinity',
 'silky shark',
 'hammerhead',
 'white shark according  witnesses',
 'bull  tiger shark',
 'bull shark suspected due  freshwater habitat',
 'reported  involve  white shark',
 'unidentified',
 'questionable incident',
 'possibly  bronze whaler shark',
 'tiger shark  female',
 'thought  involve   white shark',
 'pack   sharks',
 'said  involve   shark',
 'whitetip reef shark',
 'thresher shark',
 'white sharks',
 'shark involvement prior  death was not confirmed',
 'foot shark',
 'thought  involve  tiger shark',
 'sevengill  shark',
 'shark seen  the vicinity',
 'possibly   bull shark',
 'bull shark  caribbean reef shark',
 'thought  involve  bull shark',
 'said  involve   white shark',
 'shark involvement suspected but not confirmed',
 'white shark tooth fragments recovered',
 'salmon shark',
 'small nurse shark',
 'sharks averaged   length',
 'possibly  spinner shark',
 'bull sharks',
 'school  sharks',
 'small hammerhead shark',
 'wobbegong',
 'white shark tooth fragment recovered',
 'whale shark',
 'possibly   blacktip  spinner shark',
 'possibly  leucas',
 'shark involvement doubtful',
 'female shark',
 'silvertip shark',
 'shovelnose shark',
 'said     shark',
 'shark involvement probable',
 'white shark  tooth fragment recovered',
 'large shark',
 'bronze whaler',
 'grey shark',
 'shark probable bull shark',
 'possibly  sand shark',
 'juvenile dusky shark',
 'reported  involve  hammerhead shark',
 '�',
 '�small� shark',
 'possibly  bull shark  tiger shark',
 'said  involve      white shark',
 'shark involvement unconfirmed',
 'possibly  small blacktip shark',
 'white shark named �spotty�',
 'tawny nurse shark',
 'white shark identification   nakaya',
 'large white shark was filmed  divers   local wreck  days prior  the incident',
 'said  involve  sharks',
 'oceanic whitetip shark  female',
 'shark involvement not cofirmed',
 'survivors said  species  sharks were involved  oceanic whitetip sharks and another species',
 'shark involvement questionable',
 'white shark   bronze whaler',
 'thought  involve  bronze whale shark',
 'shark possibly whitetip reef shark',
 'shark tooth fragments recovered',
 'shark involvement prior  death could not  determined',
 'small slibrown shark',
 'bronze whaler shark   juvenile',
 'unidentified shark',
 'hammerhead sharko',
 'spinner  bull shark',
 'wobbegong shark  barbatus   identified   whitley',
 'tiger shark tooth fragment recovered',
 'white shark   based  tooth pattern',
 'white shark   female',
 'bitten  several  sharks',
 'white shark  species identity confirmed  tooth fragment',
 'tiger shark said',
 'raggedtooth shark  yearold captive female',
 'cow shark',
 'bronze whaler shark  identified  clyde buttery',
 'reported  involve   shark possibly  white shark',
 'shark possibly  mako shark',
 'thought  involve    tubar�  gralha preta    blacktip shark  limbatus',
 'shark involvement not confirmed  highly unlikely',
 'tiger shark  others',
 'blue shark    feet',
 'bull sharks     length',
 'lemon shark  bull shark',
 'less than',
 'sharks attacked survivors  the water',
 'shark possibly  blactip  spinner shark',
 'sharks teeth found embedded  the woodwork  the boat',
 'lemon shark  female',
 'remains recovered fro sharks',
 'possibly  porbeagle shark',
 'bronze whaler  tiger shark',
 'blue  porbeagle shark',
 'teeth  hull identified  those froa white shark   length',
 'white shark  identity confirmed  tooth fragment witness and photograph  captured shark',
 'female white shark named notchfin',
 'spurdog',
 'shark involvement not confirmed officials considered barracua',
 'thought  involve  mako shark but possibly  sea lion',
 'macrurus captured  hours after attack with tissue removed froman  its gut species identified   whitley  reported   obscurus    steel',
 'mako shark tooth fragments recovered',
 'shark possibly  dusky shark',
 'thought  involve  mako  grey nurse shark',
 'possibly  caribbean reef shark',
 'jan his remains washed ashore   tiger shark thought   involved',
 'five   sharks',
 'zambezi shark tooth fragments recovered',
 'tooth fragment   white shark recovered authorities believed shark was   total length',
 'cto     bite diameter just below left knee',
 'hammerhead shark then    other sharks were said    involved',
 'blind  brown shark',
 'small bull sharks',
 'nurse shark   identified    clark  description  shark',
 'shark species identity questionable',
 'shark involvement  questionable',
 'remains recovered fro white shark',
 'porbeagle  white shark',
 'white shark  oceanic whitetip shark',
 'alleged  involve  white shark',
 'large tiger shark seen  the vicinity the following morning',
 'white shark  bronze whaler',
 'two  sharks',
 'blacktip shark pup',
 'said  involve   blue shark',
 'said  involve  grey nurse shark that leapt out  the water and  seized the boy but species identification  questionable',
 'white shark species identity confirmed  tooth pattern',
 'zambesi shark   female',
 'blue nosed shark',
 'white shark   immature female previously injured',
 'said  involve  white shark but shark involvement not confirmed',
 'soupfin shark',
 'lemon shark  male  breviostris identified   stark  later the same day   pregnant female lemon shark bit the bow  the boat',
 'reef shark        greycolored shark',
 'blue nose shark',
 'caribbean reef sharks',
 'tiger shark  captured',
 'small dusky shark  blackfin shark',
 'sharks most were oceanic whitetip sharks',
 'mako shark  tooth fragment recovered  identified   nichols',
 'sixgill  sevengill shark',
 'shark  sharks serrated tooth recovered frotoe',
 'shark involvement prior  death remains unconfirmed',
 'said  involve  large mako shark',
 'hammerhead  bonnethed shark',
 'sandtiger shark   male',
 'blue shark bites present',
 'shark possibly  dusky  blacktip shark',
 'white shark  identifed    follett  tooth marks',
 'white shark white shark',
 'shark seen  area previous week',
 'questionable',
 'gummy shark rhizoprionodon  loxodon',
 'thought  involve   lemon shark two lemon sharks caught within  yds  the site  week prior    week after this incident',
 'white shark   male',
 'lemon shark  sandtiger shark',
 'shovelnosed guitarfish',
 'ground shark',
 'said  involve  oceanic whitetip shark',
 'nurse shark   identified     schultz  photograph',
 'cto     blacktip  spinner shark',
 'tawney nurse shark',
 'salmon shark suspected but unlikely',
 'white shark  sevengill shark',
 'blue whaler',
 'shark caught later',
 'possibly  white shark',
 'possibly  blacktip shark',
 'said  involve   shark but more likely damage caused  debris',
 'possibly  sandbar shark  small blacktip shark',
 'leopard shark  triakis semifasciata identified   dewitt',
 'tintorero',
 'shark known  old tom',
 'small shark with whitetipped dorsal fin',
 'spinner  blacktip sharks',
 'thought  involve  blacktip shark',
 'whaler shark captured  days later with his remains  its gut',
 'species unidentified',
 'nurse shark juvenile',
 'allegedly  foot shark',
 'fishermen recovered partial remains froshark  week later',
 'whaler',
 'thought  involve    bull shark',
 'cto     shark',
 'believed white shark and other smaller species  sharks involved',
 'captive shark',
 'hooked shark',
 'not authenticated',
 'shark involvement not confirmed injury may  due   stingray',
 'blackfin shark',
 'blue shark bites post mortem',
 'tiger shark  tooth fragment recovered frowound',
 'maculpinnis   limbatus',
 'dead blue shark',
 'possibly  small hammerhead shark',
 'shark had  very large girth',
 'white shark  gill shark',
 'dooley believed his injury was caused  stingray dasyatidae family',
 'szots right hand found     tiger shark caught   safety bay south  freemantle',
 'possibly     sandtiger shark',
 'shovelnose guitarfish adult male',
 'possibly juvenile tiger shark',
 'shark later captured  mitchellhedges',
 'said  involve hammerhead sharks',
 'gaffed shark',
 'shark involvement  not confirmed',
 'atkins remains were recovered froa dusky shark  obscurus  capt   young shark fisherman',
 'leopard shark',
 'small reef shark',
 'small browncolored shark',
 'unknown possibly  white shark',
 'possibly   blacktip shark',
 'black tipped shark',
 'said  involve   red shark',
 'raggedtooth shark    gaffed',
 'shark hindered recovery  body',
 'gray reef shark',
 'said  involved      shark',
 'reported   shark attack the story was  hoax',
 'white shark based  bite pattern',
 'blacktip  sandbar shark',
 'shark  may have been another shark nearby',
 'white shark  mtooth fragment  recovered frothe hull',
 'hammerhead sharks nearby',
 'shark involvement prior  death still   determined',
 'white shark tooth fragment recovered froankle  identified     follett',
 'white shark   according  witnesses',
 'two     sharks',
 'shark possibly  tiger shark',
 'port jackson shark',
 'white shark species identity confirmed  tooth fragment',
 'thought  involve  oceanic whitetip shark   white shark',
 'blue sharks',
 'not  shark attack  was  hoax',
 'tiger shark   tooth fragments retrieved frohis wounds',
 'whaler shark      identified   whitley',
 'shark with  very flat head� that had followed the boat for  days',
 'white shark identified  tooth pattern',
 'comrades saw sharks tail appear about  away',
 'lemon shark     tooth fragment recovered',
 'tooth fragments  �whaler� shark were recovered  bull shark according  edwards',
 'white shark     male',
 'yellow belly captive shark shark destroyed  aquariustaff next day',
 'white shark tooth fragments recovered frohull  boat',
 'white shark   tooth fragment recovered frovictims shoulder  identified   nicholls',
 'shark possibly  bull shark',
 'sharks involved',
 'thought  involve  cookie cutter shark',
 'long thin browncolored shark',
 'possibly     bull shark',
 'bull sandbar  dusky shark',
 'grey reef shark identified   menisorrah   hobson  mautin   reese',
 'several sharks involved',
 'blacktip shark  spinner shark',
 'bronze whaler shark  identified   whitley based  description',
 'little shark',
 'spinner shark  blacktip shark',
 'probable bluefish bite',
 'blue shark  blue shark',
 'unknown',
 'said  involve  grey nurse shark',
 'shark involvement not confirmed injury may have been caused   bluefish',
 'tiger shark    caught dec',
 'lemon shark   immature male identified    springer',
 'unknown but  was reported that  shark tooth was recovered frothe wound',
 'white shark  identified     follett  tooth marks',
 'identified  carcharinid shark based  its behavior     schultz mako shark according  huges',
 'said  involve  shark',
 'lemon shark  identified   the surfer',
 'hammerhead shark  according  lifeguard sabarrows',
 'tiger shark    feet',
 'juvenile dusky  blacktip shark',
 'dogfish',
 'description  shark does not ring true',
 'white shark      according  shreuder and  witness',
 'tiger shark    female',
 'hooked  shot white shark',
 'bronze whaler sharks',
 'bull shark  lemon shark',
 'longfin mako shark',
 'reported  involve  bull shark',
 'zambezi shark',
 'tiger shark caught  hours later with shorts  the boy  its gut',
 'small spotted catshark scyliorhinus canicula',
 'shark was seen  the area  witnesses',
 'bull  lemon shark',
 'white shark  thresher shark',
 'shark  shark',
 'tiger shark caught  days later with diver� remains  its gut',
 'blue whaler galeolamna',
 'said   �leopard sharks� more probably tiger sharks',
 'shark captured',
 'said    shark',
 'blacktip shark  caribbean reef shark',
 'nurse shark   identified    clark  color  tooth impressions',
 'six zambesi sharks seen    length',
 'allegedly  tiger shark',
 'two  oceanic whitetip sharks',
 'white shark    female',
 'possibly  hammerhead shark',
 'dogfish shark',
 'thought  involve  porbeagle  mako shark',
 'his hand was found    tiger shark caught',
 'days later   shark was caught  yards frothe site',
 'shark involvement probable but not confirmed',
 'whitetipped reef shark',
 'white shark tooth  recovered froboat',
 'white shark   identity confirmed  tooth pattern',
 'tiger sharks  area',
 'next morning   shark was caught that had andrews leg  its gut',
 'tiger shark     female contained girvans remains',
 'white shark       identified    shroeder based  tooth fragment ebedded  gunwale',
 'reported  media  shark attack but shark involvement prior  death was not confirmed',
 'grey reef shark  grey reef shark identified     schultz based  photographs identified   melanopterus  stewart',
 'possibly  lemon shark',
 'mako shark aka bonito shark',
 'alleged  involve  white shark with little yellow eyes',
 'possibly  broadnose gill shark',
 '� caribbean reef shark',
 'metre shark',
 'thought  involve     shark but shark involvement not confirmed',
 'large hammerhead shark',
 'blue pointers',
 'small carpet shark',
 'whale',
 'white shark  female',
 'possibly  blue shark',
 'identified   gangeticus    fayrer',
 'shark possibly  spinner shark',
 'shark shark caught  its jaw exhibited  the carnegie museum',
 'white shark  tooth fragment frowounds identified  that   white shark',
 'bonita sharkk',
 'shark seen feeding  turtle scraps thrown overboard prior  incident',
 'tiger sharks',
 'shark involvement  his death uncofirmed',
 'white shark      male',
 'according  carlsmith the sharks mouth was  wide',
 'possibly   lemon shark',
 'caribbean reef shark carcharhinus  perezi',
 'leucas tooth fragment recovered frokayak',
 'mako shark  identified  tooth fragments   whitley',
 'banjo shark',
 'white shark species identity confirmed  witnesses  tooth pattern  surfboard',
 'tooth fragments recovered frohull',
 'juvenile white shark',
 'white shark according  tooth pattern and witnesses',
 'nurse shark  cto',
 'remains recovered  days later',
 'black finned shark',
 'white shark  identified     follett  tooth fragments',
 'female blue fin shark',
 'doubtful  unconfirmed attack  unable  verify  local records',
 'blacktipped shark',
 'shark observed  area',
 'broadnose sevengill shark',
 'cookie cutter shark',
 'bull shark  was captured  dragged  the sand where tissue taken froeggink was found  its gut species identification  was made   springer based   photographs  the shark',
 'species unknown possible white shark',
 'thought  involve   grey nurse shark',
 'blue nose sharks',
 'possibly  larger shark',
 'said  involve   white shark but thought  that  was more likely  blue shark',
 'shark landed  hours later',
 'small catsharks',
 'white shark identified   hugh smith',
 'mako shark   identified     schultz  photograph',
 'remains found     shark caught  baker� haulover miami beach  oct',
 'starry smoothhound shark',
 'nurse shark    male',
 'aimarginatus',
 'bull shark identified  capt  gray',
 'white shark    juvenile',
 'thought  involve   bull shark',
 'shark possibly  blacktip',
 'said  involve white shark but species identify questionable',
 'blacktail reef shark',
 'tiger shark pregnant',
 'possibly    zambezi shark',
 'said  involve  tiger shark',
 'attacked   number  sharks',
 'bull shark according  some  the divers  the boat',
 'brown shark',
 'sand shark listed  questionable incident',
 'tiger shark less than',
 'blacktip reef shark pup',
 'bull shark caught leg recovered  buried beside the mans body',
 'horn shark heterodontus francisci',
 'shark either  bronze whaler   grey nurse shark',
 'very large shark',
 'possibly white sharks',
 'bluenosed shark',
 'possibly     blacktip  spinner shark',
 'unknown but the shark was caught and put  exhibition',
 'gray shark',
 'white shark identified  witnesses  tooth marks',
 'anglers fronew zealand caught     shark  the same spot  was believed this was the same shark that killed alysha',
 'white shark  seen  area and hooked  days later',
 'small bull shark',
 '�small brown shark�',
 'though  involve  tiger shark',
 'believed  involve   white shark',
 'thought  involve bull sharks',
 'thought  involve  juvenile hammerhead shark',
 'scalloped hammerhead sharks',
 'though  involve  white shark',
 'possiby white shark',
 'bull shark  was speared  killed',
 'shark seen with the mans body  its mouth but shark involvement prior  death was not confirmed',
 'thought  involve  white shark named kong',
 'remains recovered froshark caught days later',
 'bull shark   bull shark',
 'considered  doubtful incident',
 'sevengill shark  was caught  the vicinity',
 'grey colored shark',
 'small blue shark',
 'mako shark gaffed',
 'burgess  isaf announced the injury was the bite      year old white shark subsequent investigation revealed there was   shark involvement  this incident',
 'most likely  small shark',
 'species unknown possibly  white shark',
 'two sharks teeth recovered frocanoe',
 'questionable incident  shark bite may have precipitated drowning',
 'shark  probably  blacktip  spinner shark',
 'said  involve  tiger shark   hammerhead shark',
 'unconfirmed incident',
 'tiger sharks  bull sharks  sharks  all',
 'reportedly oceanic whitetip sharks blue sharks tiger sharks  bull sharks',
 'sandshark',
 'white shark identified   smale',
 'possibly  tiger shark',
 'lesser spotted dogfish scyliorhinus canicula less than  cin length',
 'tiger shark    shark',
 'great hammerhead shark',
 'whtietip reef shark',
 'shark spinner shark',
 'mako shark      with hook  wire leader caught  mouth',
 'moreno� leg   part  his swisuit found   shark caught two hours after the attack identified  carcharhinid shark   schultz   limbaugh  photograph',
 'thresher  blue shark the shark  was killed following the incident',
 'raggedtooth shark  tooth fragment recovered',
 'grey reef shark identified   hobson  mautin   reese',
 'thought  involve  bull  tiger shark',
 'white shark  identity confirmed  witness  tooth pattern',
 'large tiger shark',
 'possibily     sandtiger shark',
 'questionable incident reported  shark attack but thought  involve  pinniped instead',
 'shark was said  �have  very rough ��thick skin�',
 'miami   cblacktip  shark and two  cbamboo catsharks',
 'possibly  blacktip reef shark',
 'said  involve   hammerhead shark',
 'numerous dusky sharks         tiger shark',
 'according  benjamin the injury was inflicted   barracuda not  shark',
 'local authorities speculated that the water was too cold for sharks but    pregnant sandbar shark was caught next day',
 'goblin shark',
 'yearold pound pregnant blacktip reef shark',
 'spinner  blacktip shark',
 'small spinner shark',
 'bronze whaler shark   tooth was embedded  the speargun',
 'thought  involve  small sand shark',
 'shark possibly   blacktip  spinner shark',
 'porbeagle',
 'white shark identified  tooth fragments  surfboard',
 'said    �small shark�',
 'hand found  gut      galapagos shark  galapagensis',
 'pack  sharks',
 'young shark',
 'dusky shark  dusky shark  obscurus identified   springer  tooth recovered',
 'hammerhead shark   zygena identified   limbaugh  description',
 'oceanic whitetip sharks were  the vicinity',
 'blacktip shark  maculipinnis',

In [71]:
# List of shark species

shark_list = ["thresher", "grey","small","foot","goblin","silvertip","sevengill", "cocktail","bonita","whale","basket","angel","dog", "leopard","shovelnose", "red","raggedtooth","gummy", "bronze whaler", "galapagos", "sand", "wobbegong", "white ", "tiger", "lemon", "blue", "gray", "hammerhead", "spinner", "brown", "whitetip", "blacktip", "bull", "zambezi", "banjo", "nurse", "blue nose", "salmon", "mako", "blue pointer","porbeagle", "cow", "reef","smoothhound", "dogfish", "dusky"]

# new column
df["mSpecies"] = df["nSpecies"]

# find shark species 
for i in shark_list:
    df.loc[df["nSpecies"].str.contains(i).fillna(False), ["mSpecies"]] = i


# Drop all values not in shark list

df = df[df['mSpecies'].isin(shark_list)]

In [72]:
df = df.drop(columns=["Time","original order","nSpecies","Species"])

In [73]:
df = df.reset_index()

In [74]:
df.dtypes

index                              int64
Date                      datetime64[ns]
Type                              object
Country                           object
Area                              object
Location                          object
Activity                          object
Name                              object
Sex_Male                          object
Age                               object
Injury                            object
Fatal                             object
Investigator or Source            object
href                              object
newAge                            object
time_hours                        object
mSpecies                          object
dtype: object

In [75]:
# Make Sex Male, Age and Fatal to numeric

df['Sex_Male'] = pd.to_numeric(df['Sex_Male'], errors='coerce')
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Fatal'] = pd.to_numeric(df['Fatal'], errors='coerce')
df['time_hours'] = pd.to_numeric(df['time_hours'], errors='coerce')

In [76]:
# Check numeric columns with describe

df.describe()

             index     Sex_Male          Age        Fatal   time_hours
count  1916.000000  1749.000000  1245.000000  1899.000000  1751.000000
mean   2387.072547     0.889651    28.714859     0.164824     7.556254
std    1477.759363     0.313414    13.512938     0.371119     6.409467
min       7.000000     0.000000     3.000000     0.000000     1.000000
25%    1191.750000     1.000000    19.000000     0.000000     1.000000
50%    2296.000000     1.000000    25.000000     0.000000     8.000000
75%    3508.750000     1.000000    37.000000     0.000000    14.000000
max    5986.000000     1.000000    84.000000     1.000000    23.000000

In [77]:
df = df.drop(columns="index")

In [78]:
# display fraction of missing cell count per column of total cells


null_columns = df.isna().sum()
null_columns[null_columns.gt(0)]/len(df)

Date                      0.038100
Country                   0.001566
Area                      0.038622
Location                  0.045407
Activity                  0.049061
Name                      0.016701
Sex_Male                  0.087161
Age                       0.350209
Injury                    0.002088
Fatal                     0.008873
Investigator or Source    0.001566
newAge                    0.002610
time_hours                0.086117
dtype: float64

In [79]:
# Only column with high number of missing values is Age, which is not very important. 
# It is probably still a representative subset.
# Therefore nan rows or column are not dropped

In [80]:
# Rename mSpecies to Species and newAge to Age and time_hours to Time_Hours

df = df.rename(columns={"mSpecies":"Species", "newAge":"Age", "time_hours":"Time_Hours"})

In [81]:
df

,Date,Type,Country,Area,Location,Activity,Name,Sex_Male,Age,Injury,Fatal,Investigator or Source,href,Age,Time_Hours,Species
0,2016-09-07,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,0.0,51.0,Severe lacerations to shoulder & forearm,0.0,"Hawaii News Now, 9/7/2016",http://sharkattackfile.net/spreadsheets/pdf_di...,51,14.0,tiger
1,2016-09-01,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,1.0,22.0,Two toes broken & lacerated,0.0,"R. Collier, GSAF",http://sharkattackfile.net/spreadsheets/pdf_di...,22,1.0,white
2,2016-08-29,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,1.0,25.0,Lacerations to right foot,0.0,"News Channel 8, 8/30/16",http://sharkattackfile.net/spreadsheets/pdf_di...,25,15.0,bull
3,2016-08-27,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,1.0,20.0,"Right arm severed, ankle severely bitten",0.0,"LaDepeche, 8/29/2016",http://sharkattackfile.net/spreadsheets/pdf_di...,20,17.0,bull
4,2016-08-06,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,1.0,21.0,"No inury, shark & board collided",0.0,"SUP, 8/9/2015",http://sharkattackfile.net/spreadsheets/pdf_di...,21,1.0,tiger
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,NaT,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,1.0,16.0,FATAL,1.0,Mitchell-Hedges,http://sharkattackfile.net/spreadsheets/pdf_di...,16,1.0,tiger
1912,1906-01-01,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,1.0,NaN,"FATAL, knocked overboard by tail of shark & ca...",1.0,"NY Sun, 9/9/1906, referring to account by Loui...",http://sharkattackfile.net/spreadsheets/pdf_di...,1,1.0,blue pointer
1913,1906-01-01,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,1.0,NaN,FATAL,1.0,"NY Sun, 9/9/1906, referring to account by Loui...",http://sharkattackfile.net/spreadsheets/pdf_di...,1,1.0,blue pointer
1914,1906-01-01,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,1.0,NaN,FATAL,1.0,"NY Sun, 9/9/1906, referring to account by Loui...",http://sharkattackfile.net/spreadsheets/pdf_di...,1,1.0,blue pointer
1915,1906-01-01,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,1.0,NaN,FATAL,1.0,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",http://sharkattackfile.net/spreadsheets/pdf_di...,1,1.0,nurse

In [82]:
# Export as csv

df.to_csv("sharkattack_clean.csv")